// Code generated by ent, DO NOT EDIT.

package channel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldName, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldBaseURL, v))
}

// ErrorMsg applies equality check predicate on the "error_msg" field. It's identical to ErrorMsgEQ.
func ErrorMsg(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldErrorMsg, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldPriority, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldWeight, v))
}

// MaxConcurrency applies equality check predicate on the "max_concurrency" field. It's identical to MaxConcurrencyEQ.
func MaxConcurrency(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldMaxConcurrency, v))
}

// MaxRpm applies equality check predicate on the "max_rpm" field. It's identical to MaxRpmEQ.
func MaxRpm(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldMaxRpm, v))
}

// CostRatio applies equality check predicate on the "cost_ratio" field. It's identical to CostRatioEQ.
func CostRatio(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldCostRatio, v))
}

// TestModel applies equality check predicate on the "test_model" field. It's identical to TestModelEQ.
func TestModel(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTestModel, v))
}

// ResponseTimeMs applies equality check predicate on the "response_time_ms" field. It's identical to ResponseTimeMsEQ.
func ResponseTimeMs(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldResponseTimeMs, v))
}

// TestedAt applies equality check predicate on the "tested_at" field. It's identical to TestedAtEQ.
func TestedAt(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTestedAt, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldBalance, v))
}

// BalanceUpdatedAt applies equality check predicate on the "balance_updated_at" field. It's identical to BalanceUpdatedAtEQ.
func BalanceUpdatedAt(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldBalanceUpdatedAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldLastUsedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldType, vs...))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContainsFold(FieldBaseURL, v))
}

// ModelMappingIsNil applies the IsNil predicate on the "model_mapping" field.
func ModelMappingIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldModelMapping))
}

// ModelMappingNotNil applies the NotNil predicate on the "model_mapping" field.
func ModelMappingNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldModelMapping))
}

// ParamOverrideIsNil applies the IsNil predicate on the "param_override" field.
func ParamOverrideIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldParamOverride))
}

// ParamOverrideNotNil applies the NotNil predicate on the "param_override" field.
func ParamOverrideNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldParamOverride))
}

// HeaderOverrideIsNil applies the IsNil predicate on the "header_override" field.
func HeaderOverrideIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldHeaderOverride))
}

// HeaderOverrideNotNil applies the NotNil predicate on the "header_override" field.
func HeaderOverrideNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldHeaderOverride))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldStatus, vs...))
}

// ErrorMsgEQ applies the EQ predicate on the "error_msg" field.
func ErrorMsgEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldErrorMsg, v))
}

// ErrorMsgNEQ applies the NEQ predicate on the "error_msg" field.
func ErrorMsgNEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldErrorMsg, v))
}

// ErrorMsgIn applies the In predicate on the "error_msg" field.
func ErrorMsgIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldErrorMsg, vs...))
}

// ErrorMsgNotIn applies the NotIn predicate on the "error_msg" field.
func ErrorMsgNotIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldErrorMsg, vs...))
}

// ErrorMsgGT applies the GT predicate on the "error_msg" field.
func ErrorMsgGT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldErrorMsg, v))
}

// ErrorMsgGTE applies the GTE predicate on the "error_msg" field.
func ErrorMsgGTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldErrorMsg, v))
}

// ErrorMsgLT applies the LT predicate on the "error_msg" field.
func ErrorMsgLT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldErrorMsg, v))
}

// ErrorMsgLTE applies the LTE predicate on the "error_msg" field.
func ErrorMsgLTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldErrorMsg, v))
}

// ErrorMsgContains applies the Contains predicate on the "error_msg" field.
func ErrorMsgContains(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContains(FieldErrorMsg, v))
}

// ErrorMsgHasPrefix applies the HasPrefix predicate on the "error_msg" field.
func ErrorMsgHasPrefix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasPrefix(FieldErrorMsg, v))
}

// ErrorMsgHasSuffix applies the HasSuffix predicate on the "error_msg" field.
func ErrorMsgHasSuffix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasSuffix(FieldErrorMsg, v))
}

// ErrorMsgEqualFold applies the EqualFold predicate on the "error_msg" field.
func ErrorMsgEqualFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEqualFold(FieldErrorMsg, v))
}

// ErrorMsgContainsFold applies the ContainsFold predicate on the "error_msg" field.
func ErrorMsgContainsFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContainsFold(FieldErrorMsg, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldPriority, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldWeight, v))
}

// MaxConcurrencyEQ applies the EQ predicate on the "max_concurrency" field.
func MaxConcurrencyEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyNEQ applies the NEQ predicate on the "max_concurrency" field.
func MaxConcurrencyNEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyIn applies the In predicate on the "max_concurrency" field.
func MaxConcurrencyIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyNotIn applies the NotIn predicate on the "max_concurrency" field.
func MaxConcurrencyNotIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyGT applies the GT predicate on the "max_concurrency" field.
func MaxConcurrencyGT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldMaxConcurrency, v))
}

// MaxConcurrencyGTE applies the GTE predicate on the "max_concurrency" field.
func MaxConcurrencyGTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldMaxConcurrency, v))
}

// MaxConcurrencyLT applies the LT predicate on the "max_concurrency" field.
func MaxConcurrencyLT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldMaxConcurrency, v))
}

// MaxConcurrencyLTE applies the LTE predicate on the "max_concurrency" field.
func MaxConcurrencyLTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldMaxConcurrency, v))
}

// MaxRpmEQ applies the EQ predicate on the "max_rpm" field.
func MaxRpmEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldMaxRpm, v))
}

// MaxRpmNEQ applies the NEQ predicate on the "max_rpm" field.
func MaxRpmNEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldMaxRpm, v))
}

// MaxRpmIn applies the In predicate on the "max_rpm" field.
func MaxRpmIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldMaxRpm, vs...))
}

// MaxRpmNotIn applies the NotIn predicate on the "max_rpm" field.
func MaxRpmNotIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldMaxRpm, vs...))
}

// MaxRpmGT applies the GT predicate on the "max_rpm" field.
func MaxRpmGT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldMaxRpm, v))
}

// MaxRpmGTE applies the GTE predicate on the "max_rpm" field.
func MaxRpmGTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldMaxRpm, v))
}

// MaxRpmLT applies the LT predicate on the "max_rpm" field.
func MaxRpmLT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldMaxRpm, v))
}

// MaxRpmLTE applies the LTE predicate on the "max_rpm" field.
func MaxRpmLTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldMaxRpm, v))
}

// CostRatioEQ applies the EQ predicate on the "cost_ratio" field.
func CostRatioEQ(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldCostRatio, v))
}

// CostRatioNEQ applies the NEQ predicate on the "cost_ratio" field.
func CostRatioNEQ(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldCostRatio, v))
}

// CostRatioIn applies the In predicate on the "cost_ratio" field.
func CostRatioIn(vs ...float64) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldCostRatio, vs...))
}

// CostRatioNotIn applies the NotIn predicate on the "cost_ratio" field.
func CostRatioNotIn(vs ...float64) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldCostRatio, vs...))
}

// CostRatioGT applies the GT predicate on the "cost_ratio" field.
func CostRatioGT(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldCostRatio, v))
}

// CostRatioGTE applies the GTE predicate on the "cost_ratio" field.
func CostRatioGTE(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldCostRatio, v))
}

// CostRatioLT applies the LT predicate on the "cost_ratio" field.
func CostRatioLT(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldCostRatio, v))
}

// CostRatioLTE applies the LTE predicate on the "cost_ratio" field.
func CostRatioLTE(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldCostRatio, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldTags))
}

// TestModelEQ applies the EQ predicate on the "test_model" field.
func TestModelEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTestModel, v))
}

// TestModelNEQ applies the NEQ predicate on the "test_model" field.
func TestModelNEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldTestModel, v))
}

// TestModelIn applies the In predicate on the "test_model" field.
func TestModelIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldTestModel, vs...))
}

// TestModelNotIn applies the NotIn predicate on the "test_model" field.
func TestModelNotIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldTestModel, vs...))
}

// TestModelGT applies the GT predicate on the "test_model" field.
func TestModelGT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldTestModel, v))
}

// TestModelGTE applies the GTE predicate on the "test_model" field.
func TestModelGTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldTestModel, v))
}

// TestModelLT applies the LT predicate on the "test_model" field.
func TestModelLT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldTestModel, v))
}

// TestModelLTE applies the LTE predicate on the "test_model" field.
func TestModelLTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldTestModel, v))
}

// TestModelContains applies the Contains predicate on the "test_model" field.
func TestModelContains(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContains(FieldTestModel, v))
}

// TestModelHasPrefix applies the HasPrefix predicate on the "test_model" field.
func TestModelHasPrefix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasPrefix(FieldTestModel, v))
}

// TestModelHasSuffix applies the HasSuffix predicate on the "test_model" field.
func TestModelHasSuffix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasSuffix(FieldTestModel, v))
}

// TestModelEqualFold applies the EqualFold predicate on the "test_model" field.
func TestModelEqualFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEqualFold(FieldTestModel, v))
}

// TestModelContainsFold applies the ContainsFold predicate on the "test_model" field.
func TestModelContainsFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContainsFold(FieldTestModel, v))
}

// ResponseTimeMsEQ applies the EQ predicate on the "response_time_ms" field.
func ResponseTimeMsEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldResponseTimeMs, v))
}

// ResponseTimeMsNEQ applies the NEQ predicate on the "response_time_ms" field.
func ResponseTimeMsNEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldResponseTimeMs, v))
}

// ResponseTimeMsIn applies the In predicate on the "response_time_ms" field.
func ResponseTimeMsIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldResponseTimeMs, vs...))
}

// ResponseTimeMsNotIn applies the NotIn predicate on the "response_time_ms" field.
func ResponseTimeMsNotIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldResponseTimeMs, vs...))
}

// ResponseTimeMsGT applies the GT predicate on the "response_time_ms" field.
func ResponseTimeMsGT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldResponseTimeMs, v))
}

// ResponseTimeMsGTE applies the GTE predicate on the "response_time_ms" field.
func ResponseTimeMsGTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldResponseTimeMs, v))
}

// ResponseTimeMsLT applies the LT predicate on the "response_time_ms" field.
func ResponseTimeMsLT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldResponseTimeMs, v))
}

// ResponseTimeMsLTE applies the LTE predicate on the "response_time_ms" field.
func ResponseTimeMsLTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldResponseTimeMs, v))
}

// TestedAtEQ applies the EQ predicate on the "tested_at" field.
func TestedAtEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTestedAt, v))
}

// TestedAtNEQ applies the NEQ predicate on the "tested_at" field.
func TestedAtNEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldTestedAt, v))
}

// TestedAtIn applies the In predicate on the "tested_at" field.
func TestedAtIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldTestedAt, vs...))
}

// TestedAtNotIn applies the NotIn predicate on the "tested_at" field.
func TestedAtNotIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldTestedAt, vs...))
}

// TestedAtGT applies the GT predicate on the "tested_at" field.
func TestedAtGT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldTestedAt, v))
}

// TestedAtGTE applies the GTE predicate on the "tested_at" field.
func TestedAtGTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldTestedAt, v))
}

// TestedAtLT applies the LT predicate on the "tested_at" field.
func TestedAtLT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldTestedAt, v))
}

// TestedAtLTE applies the LTE predicate on the "tested_at" field.
func TestedAtLTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldTestedAt, v))
}

// TestedAtIsNil applies the IsNil predicate on the "tested_at" field.
func TestedAtIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldTestedAt))
}

// TestedAtNotNil applies the NotNil predicate on the "tested_at" field.
func TestedAtNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldTestedAt))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldBalance, v))
}

// BalanceUpdatedAtEQ applies the EQ predicate on the "balance_updated_at" field.
func BalanceUpdatedAtEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldBalanceUpdatedAt, v))
}

// BalanceUpdatedAtNEQ applies the NEQ predicate on the "balance_updated_at" field.
func BalanceUpdatedAtNEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldBalanceUpdatedAt, v))
}

// BalanceUpdatedAtIn applies the In predicate on the "balance_updated_at" field.
func BalanceUpdatedAtIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldBalanceUpdatedAt, vs...))
}

// BalanceUpdatedAtNotIn applies the NotIn predicate on the "balance_updated_at" field.
func BalanceUpdatedAtNotIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldBalanceUpdatedAt, vs...))
}

// BalanceUpdatedAtGT applies the GT predicate on the "balance_updated_at" field.
func BalanceUpdatedAtGT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldBalanceUpdatedAt, v))
}

// BalanceUpdatedAtGTE applies the GTE predicate on the "balance_updated_at" field.
func BalanceUpdatedAtGTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldBalanceUpdatedAt, v))
}

// BalanceUpdatedAtLT applies the LT predicate on the "balance_updated_at" field.
func BalanceUpdatedAtLT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldBalanceUpdatedAt, v))
}

// BalanceUpdatedAtLTE applies the LTE predicate on the "balance_updated_at" field.
func BalanceUpdatedAtLTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldBalanceUpdatedAt, v))
}

// BalanceUpdatedAtIsNil applies the IsNil predicate on the "balance_updated_at" field.
func BalanceUpdatedAtIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldBalanceUpdatedAt))
}

// BalanceUpdatedAtNotNil applies the NotNil predicate on the "balance_updated_at" field.
func BalanceUpdatedAtNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldBalanceUpdatedAt))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldLastUsedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.Channel {
	return predicate.Channel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, GroupsTable, GroupsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.Group) predicate.Channel {
	return predicate.Channel(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.Channel {
	return predicate.Channel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.Channel {
	return predicate.Channel(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Channel) predicate.Channel {
	return predicate.Channel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Channel) predicate.Channel {
	return predicate.Channel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Channel) predicate.Channel {
	return predicate.Channel(sql.NotPredicates(p))
}
