// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/channel"
	"github.com/DouDOU-start/airgate-core/ent/channelkey"
	"github.com/DouDOU-start/airgate-core/ent/group"
	"github.com/DouDOU-start/airgate-core/ent/usagelog"
)

// ChannelKeyCreate is the builder for creating a ChannelKey entity.
type ChannelKeyCreate struct {
	config
	mutation *ChannelKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (ckc *ChannelKeyCreate) SetName(s string) *ChannelKeyCreate {
	ckc.mutation.SetName(s)
	return ckc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableName(s *string) *ChannelKeyCreate {
	if s != nil {
		ckc.SetName(*s)
	}
	return ckc
}

// SetType sets the "type" field.
func (ckc *ChannelKeyCreate) SetType(c channelkey.Type) *ChannelKeyCreate {
	ckc.mutation.SetType(c)
	return ckc
}

// SetAPIKey sets the "api_key" field.
func (ckc *ChannelKeyCreate) SetAPIKey(s string) *ChannelKeyCreate {
	ckc.mutation.SetAPIKey(s)
	return ckc
}

// SetModels sets the "models" field.
func (ckc *ChannelKeyCreate) SetModels(s []string) *ChannelKeyCreate {
	ckc.mutation.SetModels(s)
	return ckc
}

// SetModelMapping sets the "model_mapping" field.
func (ckc *ChannelKeyCreate) SetModelMapping(m map[string]string) *ChannelKeyCreate {
	ckc.mutation.SetModelMapping(m)
	return ckc
}

// SetParamOverride sets the "param_override" field.
func (ckc *ChannelKeyCreate) SetParamOverride(m map[string]interface{}) *ChannelKeyCreate {
	ckc.mutation.SetParamOverride(m)
	return ckc
}

// SetHeaderOverride sets the "header_override" field.
func (ckc *ChannelKeyCreate) SetHeaderOverride(m map[string]string) *ChannelKeyCreate {
	ckc.mutation.SetHeaderOverride(m)
	return ckc
}

// SetStatus sets the "status" field.
func (ckc *ChannelKeyCreate) SetStatus(c channelkey.Status) *ChannelKeyCreate {
	ckc.mutation.SetStatus(c)
	return ckc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableStatus(c *channelkey.Status) *ChannelKeyCreate {
	if c != nil {
		ckc.SetStatus(*c)
	}
	return ckc
}

// SetErrorMsg sets the "error_msg" field.
func (ckc *ChannelKeyCreate) SetErrorMsg(s string) *ChannelKeyCreate {
	ckc.mutation.SetErrorMsg(s)
	return ckc
}

// SetNillableErrorMsg sets the "error_msg" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableErrorMsg(s *string) *ChannelKeyCreate {
	if s != nil {
		ckc.SetErrorMsg(*s)
	}
	return ckc
}

// SetPriority sets the "priority" field.
func (ckc *ChannelKeyCreate) SetPriority(i int) *ChannelKeyCreate {
	ckc.mutation.SetPriority(i)
	return ckc
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillablePriority(i *int) *ChannelKeyCreate {
	if i != nil {
		ckc.SetPriority(*i)
	}
	return ckc
}

// SetWeight sets the "weight" field.
func (ckc *ChannelKeyCreate) SetWeight(i int) *ChannelKeyCreate {
	ckc.mutation.SetWeight(i)
	return ckc
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableWeight(i *int) *ChannelKeyCreate {
	if i != nil {
		ckc.SetWeight(*i)
	}
	return ckc
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (ckc *ChannelKeyCreate) SetMaxConcurrency(i int) *ChannelKeyCreate {
	ckc.mutation.SetMaxConcurrency(i)
	return ckc
}

// SetNillableMaxConcurrency sets the "max_concurrency" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableMaxConcurrency(i *int) *ChannelKeyCreate {
	if i != nil {
		ckc.SetMaxConcurrency(*i)
	}
	return ckc
}

// SetMaxRpm sets the "max_rpm" field.
func (ckc *ChannelKeyCreate) SetMaxRpm(i int) *ChannelKeyCreate {
	ckc.mutation.SetMaxRpm(i)
	return ckc
}

// SetNillableMaxRpm sets the "max_rpm" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableMaxRpm(i *int) *ChannelKeyCreate {
	if i != nil {
		ckc.SetMaxRpm(*i)
	}
	return ckc
}

// SetCostRatio sets the "cost_ratio" field.
func (ckc *ChannelKeyCreate) SetCostRatio(f float64) *ChannelKeyCreate {
	ckc.mutation.SetCostRatio(f)
	return ckc
}

// SetNillableCostRatio sets the "cost_ratio" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableCostRatio(f *float64) *ChannelKeyCreate {
	if f != nil {
		ckc.SetCostRatio(*f)
	}
	return ckc
}

// SetTags sets the "tags" field.
func (ckc *ChannelKeyCreate) SetTags(s []string) *ChannelKeyCreate {
	ckc.mutation.SetTags(s)
	return ckc
}

// SetTestModel sets the "test_model" field.
func (ckc *ChannelKeyCreate) SetTestModel(s string) *ChannelKeyCreate {
	ckc.mutation.SetTestModel(s)
	return ckc
}

// SetNillableTestModel sets the "test_model" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableTestModel(s *string) *ChannelKeyCreate {
	if s != nil {
		ckc.SetTestModel(*s)
	}
	return ckc
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (ckc *ChannelKeyCreate) SetResponseTimeMs(i int) *ChannelKeyCreate {
	ckc.mutation.SetResponseTimeMs(i)
	return ckc
}

// SetNillableResponseTimeMs sets the "response_time_ms" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableResponseTimeMs(i *int) *ChannelKeyCreate {
	if i != nil {
		ckc.SetResponseTimeMs(*i)
	}
	return ckc
}

// SetTestedAt sets the "tested_at" field.
func (ckc *ChannelKeyCreate) SetTestedAt(t time.Time) *ChannelKeyCreate {
	ckc.mutation.SetTestedAt(t)
	return ckc
}

// SetNillableTestedAt sets the "tested_at" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableTestedAt(t *time.Time) *ChannelKeyCreate {
	if t != nil {
		ckc.SetTestedAt(*t)
	}
	return ckc
}

// SetLastUsedAt sets the "last_used_at" field.
func (ckc *ChannelKeyCreate) SetLastUsedAt(t time.Time) *ChannelKeyCreate {
	ckc.mutation.SetLastUsedAt(t)
	return ckc
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableLastUsedAt(t *time.Time) *ChannelKeyCreate {
	if t != nil {
		ckc.SetLastUsedAt(*t)
	}
	return ckc
}

// SetBalance sets the "balance" field.
func (ckc *ChannelKeyCreate) SetBalance(f float64) *ChannelKeyCreate {
	ckc.mutation.SetBalance(f)
	return ckc
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableBalance(f *float64) *ChannelKeyCreate {
	if f != nil {
		ckc.SetBalance(*f)
	}
	return ckc
}

// SetBalanceUpdatedAt sets the "balance_updated_at" field.
func (ckc *ChannelKeyCreate) SetBalanceUpdatedAt(t time.Time) *ChannelKeyCreate {
	ckc.mutation.SetBalanceUpdatedAt(t)
	return ckc
}

// SetNillableBalanceUpdatedAt sets the "balance_updated_at" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableBalanceUpdatedAt(t *time.Time) *ChannelKeyCreate {
	if t != nil {
		ckc.SetBalanceUpdatedAt(*t)
	}
	return ckc
}

// SetBalanceCheckEnabled sets the "balance_check_enabled" field.
func (ckc *ChannelKeyCreate) SetBalanceCheckEnabled(b bool) *ChannelKeyCreate {
	ckc.mutation.SetBalanceCheckEnabled(b)
	return ckc
}

// SetNillableBalanceCheckEnabled sets the "balance_check_enabled" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableBalanceCheckEnabled(b *bool) *ChannelKeyCreate {
	if b != nil {
		ckc.SetBalanceCheckEnabled(*b)
	}
	return ckc
}

// SetProbeEnabled sets the "probe_enabled" field.
func (ckc *ChannelKeyCreate) SetProbeEnabled(b bool) *ChannelKeyCreate {
	ckc.mutation.SetProbeEnabled(b)
	return ckc
}

// SetNillableProbeEnabled sets the "probe_enabled" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableProbeEnabled(b *bool) *ChannelKeyCreate {
	if b != nil {
		ckc.SetProbeEnabled(*b)
	}
	return ckc
}

// SetProbeModel sets the "probe_model" field.
func (ckc *ChannelKeyCreate) SetProbeModel(s string) *ChannelKeyCreate {
	ckc.mutation.SetProbeModel(s)
	return ckc
}

// SetNillableProbeModel sets the "probe_model" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableProbeModel(s *string) *ChannelKeyCreate {
	if s != nil {
		ckc.SetProbeModel(*s)
	}
	return ckc
}

// SetHealthStatus sets the "health_status" field.
func (ckc *ChannelKeyCreate) SetHealthStatus(cs channelkey.HealthStatus) *ChannelKeyCreate {
	ckc.mutation.SetHealthStatus(cs)
	return ckc
}

// SetNillableHealthStatus sets the "health_status" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableHealthStatus(cs *channelkey.HealthStatus) *ChannelKeyCreate {
	if cs != nil {
		ckc.SetHealthStatus(*cs)
	}
	return ckc
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (ckc *ChannelKeyCreate) SetConsecutiveFailures(i int) *ChannelKeyCreate {
	ckc.mutation.SetConsecutiveFailures(i)
	return ckc
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableConsecutiveFailures(i *int) *ChannelKeyCreate {
	if i != nil {
		ckc.SetConsecutiveFailures(*i)
	}
	return ckc
}

// SetConsecutiveSuccesses sets the "consecutive_successes" field.
func (ckc *ChannelKeyCreate) SetConsecutiveSuccesses(i int) *ChannelKeyCreate {
	ckc.mutation.SetConsecutiveSuccesses(i)
	return ckc
}

// SetNillableConsecutiveSuccesses sets the "consecutive_successes" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableConsecutiveSuccesses(i *int) *ChannelKeyCreate {
	if i != nil {
		ckc.SetConsecutiveSuccesses(*i)
	}
	return ckc
}

// SetLastProbeAt sets the "last_probe_at" field.
func (ckc *ChannelKeyCreate) SetLastProbeAt(t time.Time) *ChannelKeyCreate {
	ckc.mutation.SetLastProbeAt(t)
	return ckc
}

// SetNillableLastProbeAt sets the "last_probe_at" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableLastProbeAt(t *time.Time) *ChannelKeyCreate {
	if t != nil {
		ckc.SetLastProbeAt(*t)
	}
	return ckc
}

// SetUpstreamRateEnabled sets the "upstream_rate_enabled" field.
func (ckc *ChannelKeyCreate) SetUpstreamRateEnabled(b bool) *ChannelKeyCreate {
	ckc.mutation.SetUpstreamRateEnabled(b)
	return ckc
}

// SetNillableUpstreamRateEnabled sets the "upstream_rate_enabled" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableUpstreamRateEnabled(b *bool) *ChannelKeyCreate {
	if b != nil {
		ckc.SetUpstreamRateEnabled(*b)
	}
	return ckc
}

// SetUpstreamRatePath sets the "upstream_rate_path" field.
func (ckc *ChannelKeyCreate) SetUpstreamRatePath(s string) *ChannelKeyCreate {
	ckc.mutation.SetUpstreamRatePath(s)
	return ckc
}

// SetNillableUpstreamRatePath sets the "upstream_rate_path" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableUpstreamRatePath(s *string) *ChannelKeyCreate {
	if s != nil {
		ckc.SetUpstreamRatePath(*s)
	}
	return ckc
}

// SetUseUpstreamRateForCost sets the "use_upstream_rate_for_cost" field.
func (ckc *ChannelKeyCreate) SetUseUpstreamRateForCost(b bool) *ChannelKeyCreate {
	ckc.mutation.SetUseUpstreamRateForCost(b)
	return ckc
}

// SetNillableUseUpstreamRateForCost sets the "use_upstream_rate_for_cost" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableUseUpstreamRateForCost(b *bool) *ChannelKeyCreate {
	if b != nil {
		ckc.SetUseUpstreamRateForCost(*b)
	}
	return ckc
}

// SetUpstreamRate sets the "upstream_rate" field.
func (ckc *ChannelKeyCreate) SetUpstreamRate(f float64) *ChannelKeyCreate {
	ckc.mutation.SetUpstreamRate(f)
	return ckc
}

// SetNillableUpstreamRate sets the "upstream_rate" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableUpstreamRate(f *float64) *ChannelKeyCreate {
	if f != nil {
		ckc.SetUpstreamRate(*f)
	}
	return ckc
}

// SetUpstreamRateAt sets the "upstream_rate_at" field.
func (ckc *ChannelKeyCreate) SetUpstreamRateAt(t time.Time) *ChannelKeyCreate {
	ckc.mutation.SetUpstreamRateAt(t)
	return ckc
}

// SetNillableUpstreamRateAt sets the "upstream_rate_at" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableUpstreamRateAt(t *time.Time) *ChannelKeyCreate {
	if t != nil {
		ckc.SetUpstreamRateAt(*t)
	}
	return ckc
}

// SetCreatedAt sets the "created_at" field.
func (ckc *ChannelKeyCreate) SetCreatedAt(t time.Time) *ChannelKeyCreate {
	ckc.mutation.SetCreatedAt(t)
	return ckc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableCreatedAt(t *time.Time) *ChannelKeyCreate {
	if t != nil {
		ckc.SetCreatedAt(*t)
	}
	return ckc
}

// SetUpdatedAt sets the "updated_at" field.
func (ckc *ChannelKeyCreate) SetUpdatedAt(t time.Time) *ChannelKeyCreate {
	ckc.mutation.SetUpdatedAt(t)
	return ckc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ckc *ChannelKeyCreate) SetNillableUpdatedAt(t *time.Time) *ChannelKeyCreate {
	if t != nil {
		ckc.SetUpdatedAt(*t)
	}
	return ckc
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (ckc *ChannelKeyCreate) SetChannelID(id int) *ChannelKeyCreate {
	ckc.mutation.SetChannelID(id)
	return ckc
}

// SetChannel sets the "channel" edge to the Channel entity.
func (ckc *ChannelKeyCreate) SetChannel(c *Channel) *ChannelKeyCreate {
	return ckc.SetChannelID(c.ID)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (ckc *ChannelKeyCreate) AddGroupIDs(ids ...int) *ChannelKeyCreate {
	ckc.mutation.AddGroupIDs(ids...)
	return ckc
}

// AddGroups adds the "groups" edges to the Group entity.
func (ckc *ChannelKeyCreate) AddGroups(g ...*Group) *ChannelKeyCreate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return ckc.AddGroupIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (ckc *ChannelKeyCreate) AddUsageLogIDs(ids ...int) *ChannelKeyCreate {
	ckc.mutation.AddUsageLogIDs(ids...)
	return ckc
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (ckc *ChannelKeyCreate) AddUsageLogs(u ...*UsageLog) *ChannelKeyCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ckc.AddUsageLogIDs(ids...)
}

// Mutation returns the ChannelKeyMutation object of the builder.
func (ckc *ChannelKeyCreate) Mutation() *ChannelKeyMutation {
	return ckc.mutation
}

// Save creates the ChannelKey in the database.
func (ckc *ChannelKeyCreate) Save(ctx context.Context) (*ChannelKey, error) {
	ckc.defaults()
	return withHooks(ctx, ckc.sqlSave, ckc.mutation, ckc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ckc *ChannelKeyCreate) SaveX(ctx context.Context) *ChannelKey {
	v, err := ckc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ckc *ChannelKeyCreate) Exec(ctx context.Context) error {
	_, err := ckc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ckc *ChannelKeyCreate) ExecX(ctx context.Context) {
	if err := ckc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ckc *ChannelKeyCreate) defaults() {
	if _, ok := ckc.mutation.Name(); !ok {
		v := channelkey.DefaultName
		ckc.mutation.SetName(v)
	}
	if _, ok := ckc.mutation.Models(); !ok {
		v := channelkey.DefaultModels
		ckc.mutation.SetModels(v)
	}
	if _, ok := ckc.mutation.Status(); !ok {
		v := channelkey.DefaultStatus
		ckc.mutation.SetStatus(v)
	}
	if _, ok := ckc.mutation.ErrorMsg(); !ok {
		v := channelkey.DefaultErrorMsg
		ckc.mutation.SetErrorMsg(v)
	}
	if _, ok := ckc.mutation.Priority(); !ok {
		v := channelkey.DefaultPriority
		ckc.mutation.SetPriority(v)
	}
	if _, ok := ckc.mutation.Weight(); !ok {
		v := channelkey.DefaultWeight
		ckc.mutation.SetWeight(v)
	}
	if _, ok := ckc.mutation.MaxConcurrency(); !ok {
		v := channelkey.DefaultMaxConcurrency
		ckc.mutation.SetMaxConcurrency(v)
	}
	if _, ok := ckc.mutation.MaxRpm(); !ok {
		v := channelkey.DefaultMaxRpm
		ckc.mutation.SetMaxRpm(v)
	}
	if _, ok := ckc.mutation.CostRatio(); !ok {
		v := channelkey.DefaultCostRatio
		ckc.mutation.SetCostRatio(v)
	}
	if _, ok := ckc.mutation.TestModel(); !ok {
		v := channelkey.DefaultTestModel
		ckc.mutation.SetTestModel(v)
	}
	if _, ok := ckc.mutation.ResponseTimeMs(); !ok {
		v := channelkey.DefaultResponseTimeMs
		ckc.mutation.SetResponseTimeMs(v)
	}
	if _, ok := ckc.mutation.Balance(); !ok {
		v := channelkey.DefaultBalance
		ckc.mutation.SetBalance(v)
	}
	if _, ok := ckc.mutation.BalanceCheckEnabled(); !ok {
		v := channelkey.DefaultBalanceCheckEnabled
		ckc.mutation.SetBalanceCheckEnabled(v)
	}
	if _, ok := ckc.mutation.ProbeEnabled(); !ok {
		v := channelkey.DefaultProbeEnabled
		ckc.mutation.SetProbeEnabled(v)
	}
	if _, ok := ckc.mutation.ProbeModel(); !ok {
		v := channelkey.DefaultProbeModel
		ckc.mutation.SetProbeModel(v)
	}
	if _, ok := ckc.mutation.HealthStatus(); !ok {
		v := channelkey.DefaultHealthStatus
		ckc.mutation.SetHealthStatus(v)
	}
	if _, ok := ckc.mutation.ConsecutiveFailures(); !ok {
		v := channelkey.DefaultConsecutiveFailures
		ckc.mutation.SetConsecutiveFailures(v)
	}
	if _, ok := ckc.mutation.ConsecutiveSuccesses(); !ok {
		v := channelkey.DefaultConsecutiveSuccesses
		ckc.mutation.SetConsecutiveSuccesses(v)
	}
	if _, ok := ckc.mutation.UpstreamRateEnabled(); !ok {
		v := channelkey.DefaultUpstreamRateEnabled
		ckc.mutation.SetUpstreamRateEnabled(v)
	}
	if _, ok := ckc.mutation.UpstreamRatePath(); !ok {
		v := channelkey.DefaultUpstreamRatePath
		ckc.mutation.SetUpstreamRatePath(v)
	}
	if _, ok := ckc.mutation.UseUpstreamRateForCost(); !ok {
		v := channelkey.DefaultUseUpstreamRateForCost
		ckc.mutation.SetUseUpstreamRateForCost(v)
	}
	if _, ok := ckc.mutation.UpstreamRate(); !ok {
		v := channelkey.DefaultUpstreamRate
		ckc.mutation.SetUpstreamRate(v)
	}
	if _, ok := ckc.mutation.CreatedAt(); !ok {
		v := channelkey.DefaultCreatedAt()
		ckc.mutation.SetCreatedAt(v)
	}
	if _, ok := ckc.mutation.UpdatedAt(); !ok {
		v := channelkey.DefaultUpdatedAt()
		ckc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ckc *ChannelKeyCreate) check() error {
	if _, ok := ckc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ChannelKey.name"`)}
	}
	if _, ok := ckc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ChannelKey.type"`)}
	}
	if v, ok := ckc.mutation.GetType(); ok {
		if err := channelkey.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ChannelKey.type": %w`, err)}
		}
	}
	if _, ok := ckc.mutation.APIKey(); !ok {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required field "ChannelKey.api_key"`)}
	}
	if v, ok := ckc.mutation.APIKey(); ok {
		if err := channelkey.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "ChannelKey.api_key": %w`, err)}
		}
	}
	if _, ok := ckc.mutation.Models(); !ok {
		return &ValidationError{Name: "models", err: errors.New(`ent: missing required field "ChannelKey.models"`)}
	}
	if _, ok := ckc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ChannelKey.status"`)}
	}
	if v, ok := ckc.mutation.Status(); ok {
		if err := channelkey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChannelKey.status": %w`, err)}
		}
	}
	if _, ok := ckc.mutation.ErrorMsg(); !ok {
		return &ValidationError{Name: "error_msg", err: errors.New(`ent: missing required field "ChannelKey.error_msg"`)}
	}
	if _, ok := ckc.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "ChannelKey.priority"`)}
	}
	if v, ok := ckc.mutation.Priority(); ok {
		if err := channelkey.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "ChannelKey.priority": %w`, err)}
		}
	}
	if _, ok := ckc.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "ChannelKey.weight"`)}
	}
	if v, ok := ckc.mutation.Weight(); ok {
		if err := channelkey.WeightValidator(v); err != nil {
			return &ValidationError{Name: "weight", err: fmt.Errorf(`ent: validator failed for field "ChannelKey.weight": %w`, err)}
		}
	}
	if _, ok := ckc.mutation.MaxConcurrency(); !ok {
		return &ValidationError{Name: "max_concurrency", err: errors.New(`ent: missing required field "ChannelKey.max_concurrency"`)}
	}
	if _, ok := ckc.mutation.MaxRpm(); !ok {
		return &ValidationError{Name: "max_rpm", err: errors.New(`ent: missing required field "ChannelKey.max_rpm"`)}
	}
	if _, ok := ckc.mutation.CostRatio(); !ok {
		return &ValidationError{Name: "cost_ratio", err: errors.New(`ent: missing required field "ChannelKey.cost_ratio"`)}
	}
	if _, ok := ckc.mutation.TestModel(); !ok {
		return &ValidationError{Name: "test_model", err: errors.New(`ent: missing required field "ChannelKey.test_model"`)}
	}
	if _, ok := ckc.mutation.ResponseTimeMs(); !ok {
		return &ValidationError{Name: "response_time_ms", err: errors.New(`ent: missing required field "ChannelKey.response_time_ms"`)}
	}
	if _, ok := ckc.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "ChannelKey.balance"`)}
	}
	if _, ok := ckc.mutation.BalanceCheckEnabled(); !ok {
		return &ValidationError{Name: "balance_check_enabled", err: errors.New(`ent: missing required field "ChannelKey.balance_check_enabled"`)}
	}
	if _, ok := ckc.mutation.ProbeEnabled(); !ok {
		return &ValidationError{Name: "probe_enabled", err: errors.New(`ent: missing required field "ChannelKey.probe_enabled"`)}
	}
	if _, ok := ckc.mutation.ProbeModel(); !ok {
		return &ValidationError{Name: "probe_model", err: errors.New(`ent: missing required field "ChannelKey.probe_model"`)}
	}
	if _, ok := ckc.mutation.HealthStatus(); !ok {
		return &ValidationError{Name: "health_status", err: errors.New(`ent: missing required field "ChannelKey.health_status"`)}
	}
	if v, ok := ckc.mutation.HealthStatus(); ok {
		if err := channelkey.HealthStatusValidator(v); err != nil {
			return &ValidationError{Name: "health_status", err: fmt.Errorf(`ent: validator failed for field "ChannelKey.health_status": %w`, err)}
		}
	}
	if _, ok := ckc.mutation.ConsecutiveFailures(); !ok {
		return &ValidationError{Name: "consecutive_failures", err: errors.New(`ent: missing required field "ChannelKey.consecutive_failures"`)}
	}
	if _, ok := ckc.mutation.ConsecutiveSuccesses(); !ok {
		return &ValidationError{Name: "consecutive_successes", err: errors.New(`ent: missing required field "ChannelKey.consecutive_successes"`)}
	}
	if _, ok := ckc.mutation.UpstreamRateEnabled(); !ok {
		return &ValidationError{Name: "upstream_rate_enabled", err: errors.New(`ent: missing required field "ChannelKey.upstream_rate_enabled"`)}
	}
	if _, ok := ckc.mutation.UpstreamRatePath(); !ok {
		return &ValidationError{Name: "upstream_rate_path", err: errors.New(`ent: missing required field "ChannelKey.upstream_rate_path"`)}
	}
	if _, ok := ckc.mutation.UseUpstreamRateForCost(); !ok {
		return &ValidationError{Name: "use_upstream_rate_for_cost", err: errors.New(`ent: missing required field "ChannelKey.use_upstream_rate_for_cost"`)}
	}
	if _, ok := ckc.mutation.UpstreamRate(); !ok {
		return &ValidationError{Name: "upstream_rate", err: errors.New(`ent: missing required field "ChannelKey.upstream_rate"`)}
	}
	if _, ok := ckc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChannelKey.created_at"`)}
	}
	if _, ok := ckc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChannelKey.updated_at"`)}
	}
	if _, ok := ckc.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ChannelKey.channel"`)}
	}
	return nil
}

func (ckc *ChannelKeyCreate) sqlSave(ctx context.Context) (*ChannelKey, error) {
	if err := ckc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ckc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ckc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ckc.mutation.id = &_node.ID
	ckc.mutation.done = true
	return _node, nil
}

func (ckc *ChannelKeyCreate) createSpec() (*ChannelKey, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelKey{config: ckc.config}
		_spec = sqlgraph.NewCreateSpec(channelkey.Table, sqlgraph.NewFieldSpec(channelkey.FieldID, field.TypeInt))
	)
	_spec.OnConflict = ckc.conflict
	if value, ok := ckc.mutation.Name(); ok {
		_spec.SetField(channelkey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ckc.mutation.GetType(); ok {
		_spec.SetField(channelkey.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := ckc.mutation.APIKey(); ok {
		_spec.SetField(channelkey.FieldAPIKey, field.TypeString, value)
		_node.APIKey = value
	}
	if value, ok := ckc.mutation.Models(); ok {
		_spec.SetField(channelkey.FieldModels, field.TypeJSON, value)
		_node.Models = value
	}
	if value, ok := ckc.mutation.ModelMapping(); ok {
		_spec.SetField(channelkey.FieldModelMapping, field.TypeJSON, value)
		_node.ModelMapping = value
	}
	if value, ok := ckc.mutation.ParamOverride(); ok {
		_spec.SetField(channelkey.FieldParamOverride, field.TypeJSON, value)
		_node.ParamOverride = value
	}
	if value, ok := ckc.mutation.HeaderOverride(); ok {
		_spec.SetField(channelkey.FieldHeaderOverride, field.TypeJSON, value)
		_node.HeaderOverride = value
	}
	if value, ok := ckc.mutation.Status(); ok {
		_spec.SetField(channelkey.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := ckc.mutation.ErrorMsg(); ok {
		_spec.SetField(channelkey.FieldErrorMsg, field.TypeString, value)
		_node.ErrorMsg = value
	}
	if value, ok := ckc.mutation.Priority(); ok {
		_spec.SetField(channelkey.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := ckc.mutation.Weight(); ok {
		_spec.SetField(channelkey.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := ckc.mutation.MaxConcurrency(); ok {
		_spec.SetField(channelkey.FieldMaxConcurrency, field.TypeInt, value)
		_node.MaxConcurrency = value
	}
	if value, ok := ckc.mutation.MaxRpm(); ok {
		_spec.SetField(channelkey.FieldMaxRpm, field.TypeInt, value)
		_node.MaxRpm = value
	}
	if value, ok := ckc.mutation.CostRatio(); ok {
		_spec.SetField(channelkey.FieldCostRatio, field.TypeFloat64, value)
		_node.CostRatio = value
	}
	if value, ok := ckc.mutation.Tags(); ok {
		_spec.SetField(channelkey.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := ckc.mutation.TestModel(); ok {
		_spec.SetField(channelkey.FieldTestModel, field.TypeString, value)
		_node.TestModel = value
	}
	if value, ok := ckc.mutation.ResponseTimeMs(); ok {
		_spec.SetField(channelkey.FieldResponseTimeMs, field.TypeInt, value)
		_node.ResponseTimeMs = value
	}
	if value, ok := ckc.mutation.TestedAt(); ok {
		_spec.SetField(channelkey.FieldTestedAt, field.TypeTime, value)
		_node.TestedAt = &value
	}
	if value, ok := ckc.mutation.LastUsedAt(); ok {
		_spec.SetField(channelkey.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := ckc.mutation.Balance(); ok {
		_spec.SetField(channelkey.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := ckc.mutation.BalanceUpdatedAt(); ok {
		_spec.SetField(channelkey.FieldBalanceUpdatedAt, field.TypeTime, value)
		_node.BalanceUpdatedAt = &value
	}
	if value, ok := ckc.mutation.BalanceCheckEnabled(); ok {
		_spec.SetField(channelkey.FieldBalanceCheckEnabled, field.TypeBool, value)
		_node.BalanceCheckEnabled = value
	}
	if value, ok := ckc.mutation.ProbeEnabled(); ok {
		_spec.SetField(channelkey.FieldProbeEnabled, field.TypeBool, value)
		_node.ProbeEnabled = value
	}
	if value, ok := ckc.mutation.ProbeModel(); ok {
		_spec.SetField(channelkey.FieldProbeModel, field.TypeString, value)
		_node.ProbeModel = value
	}
	if value, ok := ckc.mutation.HealthStatus(); ok {
		_spec.SetField(channelkey.FieldHealthStatus, field.TypeEnum, value)
		_node.HealthStatus = value
	}
	if value, ok := ckc.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(channelkey.FieldConsecutiveFailures, field.TypeInt, value)
		_node.ConsecutiveFailures = value
	}
	if value, ok := ckc.mutation.ConsecutiveSuccesses(); ok {
		_spec.SetField(channelkey.FieldConsecutiveSuccesses, field.TypeInt, value)
		_node.ConsecutiveSuccesses = value
	}
	if value, ok := ckc.mutation.LastProbeAt(); ok {
		_spec.SetField(channelkey.FieldLastProbeAt, field.TypeTime, value)
		_node.LastProbeAt = &value
	}
	if value, ok := ckc.mutation.UpstreamRateEnabled(); ok {
		_spec.SetField(channelkey.FieldUpstreamRateEnabled, field.TypeBool, value)
		_node.UpstreamRateEnabled = value
	}
	if value, ok := ckc.mutation.UpstreamRatePath(); ok {
		_spec.SetField(channelkey.FieldUpstreamRatePath, field.TypeString, value)
		_node.UpstreamRatePath = value
	}
	if value, ok := ckc.mutation.UseUpstreamRateForCost(); ok {
		_spec.SetField(channelkey.FieldUseUpstreamRateForCost, field.TypeBool, value)
		_node.UseUpstreamRateForCost = value
	}
	if value, ok := ckc.mutation.UpstreamRate(); ok {
		_spec.SetField(channelkey.FieldUpstreamRate, field.TypeFloat64, value)
		_node.UpstreamRate = value
	}
	if value, ok := ckc.mutation.UpstreamRateAt(); ok {
		_spec.SetField(channelkey.FieldUpstreamRateAt, field.TypeTime, value)
		_node.UpstreamRateAt = &value
	}
	if value, ok := ckc.mutation.CreatedAt(); ok {
		_spec.SetField(channelkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ckc.mutation.UpdatedAt(); ok {
		_spec.SetField(channelkey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := ckc.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelkey.ChannelTable,
			Columns: []string{channelkey.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.channel_keys = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ckc.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   channelkey.GroupsTable,
			Columns: channelkey.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ckc.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelkey.UsageLogsTable,
			Columns: []string{channelkey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelKey.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelKeyUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (ckc *ChannelKeyCreate) OnConflict(opts ...sql.ConflictOption) *ChannelKeyUpsertOne {
	ckc.conflict = opts
	return &ChannelKeyUpsertOne{
		create: ckc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ckc *ChannelKeyCreate) OnConflictColumns(columns ...string) *ChannelKeyUpsertOne {
	ckc.conflict = append(ckc.conflict, sql.ConflictColumns(columns...))
	return &ChannelKeyUpsertOne{
		create: ckc,
	}
}

type (
	// ChannelKeyUpsertOne is the builder for "upsert"-ing
	//  one ChannelKey node.
	ChannelKeyUpsertOne struct {
		create *ChannelKeyCreate
	}

	// ChannelKeyUpsert is the "OnConflict" setter.
	ChannelKeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ChannelKeyUpsert) SetName(v string) *ChannelKeyUpsert {
	u.Set(channelkey.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateName() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldName)
	return u
}

// SetType sets the "type" field.
func (u *ChannelKeyUpsert) SetType(v channelkey.Type) *ChannelKeyUpsert {
	u.Set(channelkey.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateType() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldType)
	return u
}

// SetAPIKey sets the "api_key" field.
func (u *ChannelKeyUpsert) SetAPIKey(v string) *ChannelKeyUpsert {
	u.Set(channelkey.FieldAPIKey, v)
	return u
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateAPIKey() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldAPIKey)
	return u
}

// SetModels sets the "models" field.
func (u *ChannelKeyUpsert) SetModels(v []string) *ChannelKeyUpsert {
	u.Set(channelkey.FieldModels, v)
	return u
}

// UpdateModels sets the "models" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateModels() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldModels)
	return u
}

// SetModelMapping sets the "model_mapping" field.
func (u *ChannelKeyUpsert) SetModelMapping(v map[string]string) *ChannelKeyUpsert {
	u.Set(channelkey.FieldModelMapping, v)
	return u
}

// UpdateModelMapping sets the "model_mapping" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateModelMapping() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldModelMapping)
	return u
}

// ClearModelMapping clears the value of the "model_mapping" field.
func (u *ChannelKeyUpsert) ClearModelMapping() *ChannelKeyUpsert {
	u.SetNull(channelkey.FieldModelMapping)
	return u
}

// SetParamOverride sets the "param_override" field.
func (u *ChannelKeyUpsert) SetParamOverride(v map[string]interface{}) *ChannelKeyUpsert {
	u.Set(channelkey.FieldParamOverride, v)
	return u
}

// UpdateParamOverride sets the "param_override" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateParamOverride() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldParamOverride)
	return u
}

// ClearParamOverride clears the value of the "param_override" field.
func (u *ChannelKeyUpsert) ClearParamOverride() *ChannelKeyUpsert {
	u.SetNull(channelkey.FieldParamOverride)
	return u
}

// SetHeaderOverride sets the "header_override" field.
func (u *ChannelKeyUpsert) SetHeaderOverride(v map[string]string) *ChannelKeyUpsert {
	u.Set(channelkey.FieldHeaderOverride, v)
	return u
}

// UpdateHeaderOverride sets the "header_override" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateHeaderOverride() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldHeaderOverride)
	return u
}

// ClearHeaderOverride clears the value of the "header_override" field.
func (u *ChannelKeyUpsert) ClearHeaderOverride() *ChannelKeyUpsert {
	u.SetNull(channelkey.FieldHeaderOverride)
	return u
}

// SetStatus sets the "status" field.
func (u *ChannelKeyUpsert) SetStatus(v channelkey.Status) *ChannelKeyUpsert {
	u.Set(channelkey.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateStatus() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldStatus)
	return u
}

// SetErrorMsg sets the "error_msg" field.
func (u *ChannelKeyUpsert) SetErrorMsg(v string) *ChannelKeyUpsert {
	u.Set(channelkey.FieldErrorMsg, v)
	return u
}

// UpdateErrorMsg sets the "error_msg" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateErrorMsg() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldErrorMsg)
	return u
}

// SetPriority sets the "priority" field.
func (u *ChannelKeyUpsert) SetPriority(v int) *ChannelKeyUpsert {
	u.Set(channelkey.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdatePriority() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *ChannelKeyUpsert) AddPriority(v int) *ChannelKeyUpsert {
	u.Add(channelkey.FieldPriority, v)
	return u
}

// SetWeight sets the "weight" field.
func (u *ChannelKeyUpsert) SetWeight(v int) *ChannelKeyUpsert {
	u.Set(channelkey.FieldWeight, v)
	return u
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateWeight() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldWeight)
	return u
}

// AddWeight adds v to the "weight" field.
func (u *ChannelKeyUpsert) AddWeight(v int) *ChannelKeyUpsert {
	u.Add(channelkey.FieldWeight, v)
	return u
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *ChannelKeyUpsert) SetMaxConcurrency(v int) *ChannelKeyUpsert {
	u.Set(channelkey.FieldMaxConcurrency, v)
	return u
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateMaxConcurrency() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldMaxConcurrency)
	return u
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *ChannelKeyUpsert) AddMaxConcurrency(v int) *ChannelKeyUpsert {
	u.Add(channelkey.FieldMaxConcurrency, v)
	return u
}

// SetMaxRpm sets the "max_rpm" field.
func (u *ChannelKeyUpsert) SetMaxRpm(v int) *ChannelKeyUpsert {
	u.Set(channelkey.FieldMaxRpm, v)
	return u
}

// UpdateMaxRpm sets the "max_rpm" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateMaxRpm() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldMaxRpm)
	return u
}

// AddMaxRpm adds v to the "max_rpm" field.
func (u *ChannelKeyUpsert) AddMaxRpm(v int) *ChannelKeyUpsert {
	u.Add(channelkey.FieldMaxRpm, v)
	return u
}

// SetCostRatio sets the "cost_ratio" field.
func (u *ChannelKeyUpsert) SetCostRatio(v float64) *ChannelKeyUpsert {
	u.Set(channelkey.FieldCostRatio, v)
	return u
}

// UpdateCostRatio sets the "cost_ratio" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateCostRatio() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldCostRatio)
	return u
}

// AddCostRatio adds v to the "cost_ratio" field.
func (u *ChannelKeyUpsert) AddCostRatio(v float64) *ChannelKeyUpsert {
	u.Add(channelkey.FieldCostRatio, v)
	return u
}

// SetTags sets the "tags" field.
func (u *ChannelKeyUpsert) SetTags(v []string) *ChannelKeyUpsert {
	u.Set(channelkey.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateTags() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldTags)
	return u
}

// ClearTags clears the value of the "tags" field.
func (u *ChannelKeyUpsert) ClearTags() *ChannelKeyUpsert {
	u.SetNull(channelkey.FieldTags)
	return u
}

// SetTestModel sets the "test_model" field.
func (u *ChannelKeyUpsert) SetTestModel(v string) *ChannelKeyUpsert {
	u.Set(channelkey.FieldTestModel, v)
	return u
}

// UpdateTestModel sets the "test_model" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateTestModel() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldTestModel)
	return u
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (u *ChannelKeyUpsert) SetResponseTimeMs(v int) *ChannelKeyUpsert {
	u.Set(channelkey.FieldResponseTimeMs, v)
	return u
}

// UpdateResponseTimeMs sets the "response_time_ms" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateResponseTimeMs() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldResponseTimeMs)
	return u
}

// AddResponseTimeMs adds v to the "response_time_ms" field.
func (u *ChannelKeyUpsert) AddResponseTimeMs(v int) *ChannelKeyUpsert {
	u.Add(channelkey.FieldResponseTimeMs, v)
	return u
}

// SetTestedAt sets the "tested_at" field.
func (u *ChannelKeyUpsert) SetTestedAt(v time.Time) *ChannelKeyUpsert {
	u.Set(channelkey.FieldTestedAt, v)
	return u
}

// UpdateTestedAt sets the "tested_at" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateTestedAt() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldTestedAt)
	return u
}

// ClearTestedAt clears the value of the "tested_at" field.
func (u *ChannelKeyUpsert) ClearTestedAt() *ChannelKeyUpsert {
	u.SetNull(channelkey.FieldTestedAt)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *ChannelKeyUpsert) SetLastUsedAt(v time.Time) *ChannelKeyUpsert {
	u.Set(channelkey.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateLastUsedAt() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *ChannelKeyUpsert) ClearLastUsedAt() *ChannelKeyUpsert {
	u.SetNull(channelkey.FieldLastUsedAt)
	return u
}

// SetBalance sets the "balance" field.
func (u *ChannelKeyUpsert) SetBalance(v float64) *ChannelKeyUpsert {
	u.Set(channelkey.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateBalance() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *ChannelKeyUpsert) AddBalance(v float64) *ChannelKeyUpsert {
	u.Add(channelkey.FieldBalance, v)
	return u
}

// SetBalanceUpdatedAt sets the "balance_updated_at" field.
func (u *ChannelKeyUpsert) SetBalanceUpdatedAt(v time.Time) *ChannelKeyUpsert {
	u.Set(channelkey.FieldBalanceUpdatedAt, v)
	return u
}

// UpdateBalanceUpdatedAt sets the "balance_updated_at" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateBalanceUpdatedAt() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldBalanceUpdatedAt)
	return u
}

// ClearBalanceUpdatedAt clears the value of the "balance_updated_at" field.
func (u *ChannelKeyUpsert) ClearBalanceUpdatedAt() *ChannelKeyUpsert {
	u.SetNull(channelkey.FieldBalanceUpdatedAt)
	return u
}

// SetBalanceCheckEnabled sets the "balance_check_enabled" field.
func (u *ChannelKeyUpsert) SetBalanceCheckEnabled(v bool) *ChannelKeyUpsert {
	u.Set(channelkey.FieldBalanceCheckEnabled, v)
	return u
}

// UpdateBalanceCheckEnabled sets the "balance_check_enabled" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateBalanceCheckEnabled() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldBalanceCheckEnabled)
	return u
}

// SetProbeEnabled sets the "probe_enabled" field.
func (u *ChannelKeyUpsert) SetProbeEnabled(v bool) *ChannelKeyUpsert {
	u.Set(channelkey.FieldProbeEnabled, v)
	return u
}

// UpdateProbeEnabled sets the "probe_enabled" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateProbeEnabled() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldProbeEnabled)
	return u
}

// SetProbeModel sets the "probe_model" field.
func (u *ChannelKeyUpsert) SetProbeModel(v string) *ChannelKeyUpsert {
	u.Set(channelkey.FieldProbeModel, v)
	return u
}

// UpdateProbeModel sets the "probe_model" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateProbeModel() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldProbeModel)
	return u
}

// SetHealthStatus sets the "health_status" field.
func (u *ChannelKeyUpsert) SetHealthStatus(v channelkey.HealthStatus) *ChannelKeyUpsert {
	u.Set(channelkey.FieldHealthStatus, v)
	return u
}

// UpdateHealthStatus sets the "health_status" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateHealthStatus() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldHealthStatus)
	return u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (u *ChannelKeyUpsert) SetConsecutiveFailures(v int) *ChannelKeyUpsert {
	u.Set(channelkey.FieldConsecutiveFailures, v)
	return u
}

// UpdateConsecutiveFailures sets the "consecutive_failures" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateConsecutiveFailures() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldConsecutiveFailures)
	return u
}

// AddConsecutiveFailures adds v to the "consecutive_failures" field.
func (u *ChannelKeyUpsert) AddConsecutiveFailures(v int) *ChannelKeyUpsert {
	u.Add(channelkey.FieldConsecutiveFailures, v)
	return u
}

// SetConsecutiveSuccesses sets the "consecutive_successes" field.
func (u *ChannelKeyUpsert) SetConsecutiveSuccesses(v int) *ChannelKeyUpsert {
	u.Set(channelkey.FieldConsecutiveSuccesses, v)
	return u
}

// UpdateConsecutiveSuccesses sets the "consecutive_successes" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateConsecutiveSuccesses() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldConsecutiveSuccesses)
	return u
}

// AddConsecutiveSuccesses adds v to the "consecutive_successes" field.
func (u *ChannelKeyUpsert) AddConsecutiveSuccesses(v int) *ChannelKeyUpsert {
	u.Add(channelkey.FieldConsecutiveSuccesses, v)
	return u
}

// SetLastProbeAt sets the "last_probe_at" field.
func (u *ChannelKeyUpsert) SetLastProbeAt(v time.Time) *ChannelKeyUpsert {
	u.Set(channelkey.FieldLastProbeAt, v)
	return u
}

// UpdateLastProbeAt sets the "last_probe_at" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateLastProbeAt() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldLastProbeAt)
	return u
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (u *ChannelKeyUpsert) ClearLastProbeAt() *ChannelKeyUpsert {
	u.SetNull(channelkey.FieldLastProbeAt)
	return u
}

// SetUpstreamRateEnabled sets the "upstream_rate_enabled" field.
func (u *ChannelKeyUpsert) SetUpstreamRateEnabled(v bool) *ChannelKeyUpsert {
	u.Set(channelkey.FieldUpstreamRateEnabled, v)
	return u
}

// UpdateUpstreamRateEnabled sets the "upstream_rate_enabled" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateUpstreamRateEnabled() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldUpstreamRateEnabled)
	return u
}

// SetUpstreamRatePath sets the "upstream_rate_path" field.
func (u *ChannelKeyUpsert) SetUpstreamRatePath(v string) *ChannelKeyUpsert {
	u.Set(channelkey.FieldUpstreamRatePath, v)
	return u
}

// UpdateUpstreamRatePath sets the "upstream_rate_path" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateUpstreamRatePath() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldUpstreamRatePath)
	return u
}

// SetUseUpstreamRateForCost sets the "use_upstream_rate_for_cost" field.
func (u *ChannelKeyUpsert) SetUseUpstreamRateForCost(v bool) *ChannelKeyUpsert {
	u.Set(channelkey.FieldUseUpstreamRateForCost, v)
	return u
}

// UpdateUseUpstreamRateForCost sets the "use_upstream_rate_for_cost" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateUseUpstreamRateForCost() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldUseUpstreamRateForCost)
	return u
}

// SetUpstreamRate sets the "upstream_rate" field.
func (u *ChannelKeyUpsert) SetUpstreamRate(v float64) *ChannelKeyUpsert {
	u.Set(channelkey.FieldUpstreamRate, v)
	return u
}

// UpdateUpstreamRate sets the "upstream_rate" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateUpstreamRate() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldUpstreamRate)
	return u
}

// AddUpstreamRate adds v to the "upstream_rate" field.
func (u *ChannelKeyUpsert) AddUpstreamRate(v float64) *ChannelKeyUpsert {
	u.Add(channelkey.FieldUpstreamRate, v)
	return u
}

// SetUpstreamRateAt sets the "upstream_rate_at" field.
func (u *ChannelKeyUpsert) SetUpstreamRateAt(v time.Time) *ChannelKeyUpsert {
	u.Set(channelkey.FieldUpstreamRateAt, v)
	return u
}

// UpdateUpstreamRateAt sets the "upstream_rate_at" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateUpstreamRateAt() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldUpstreamRateAt)
	return u
}

// ClearUpstreamRateAt clears the value of the "upstream_rate_at" field.
func (u *ChannelKeyUpsert) ClearUpstreamRateAt() *ChannelKeyUpsert {
	u.SetNull(channelkey.FieldUpstreamRateAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelKeyUpsert) SetUpdatedAt(v time.Time) *ChannelKeyUpsert {
	u.Set(channelkey.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelKeyUpsert) UpdateUpdatedAt() *ChannelKeyUpsert {
	u.SetExcluded(channelkey.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChannelKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelKeyUpsertOne) UpdateNewValues() *ChannelKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(channelkey.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelKeyUpsertOne) Ignore() *ChannelKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelKeyUpsertOne) DoNothing() *ChannelKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelKeyCreate.OnConflict
// documentation for more info.
func (u *ChannelKeyUpsertOne) Update(set func(*ChannelKeyUpsert)) *ChannelKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ChannelKeyUpsertOne) SetName(v string) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateName() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *ChannelKeyUpsertOne) SetType(v channelkey.Type) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateType() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateType()
	})
}

// SetAPIKey sets the "api_key" field.
func (u *ChannelKeyUpsertOne) SetAPIKey(v string) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetAPIKey(v)
	})
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateAPIKey() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateAPIKey()
	})
}

// SetModels sets the "models" field.
func (u *ChannelKeyUpsertOne) SetModels(v []string) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetModels(v)
	})
}

// UpdateModels sets the "models" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateModels() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateModels()
	})
}

// SetModelMapping sets the "model_mapping" field.
func (u *ChannelKeyUpsertOne) SetModelMapping(v map[string]string) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetModelMapping(v)
	})
}

// UpdateModelMapping sets the "model_mapping" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateModelMapping() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateModelMapping()
	})
}

// ClearModelMapping clears the value of the "model_mapping" field.
func (u *ChannelKeyUpsertOne) ClearModelMapping() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearModelMapping()
	})
}

// SetParamOverride sets the "param_override" field.
func (u *ChannelKeyUpsertOne) SetParamOverride(v map[string]interface{}) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetParamOverride(v)
	})
}

// UpdateParamOverride sets the "param_override" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateParamOverride() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateParamOverride()
	})
}

// ClearParamOverride clears the value of the "param_override" field.
func (u *ChannelKeyUpsertOne) ClearParamOverride() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearParamOverride()
	})
}

// SetHeaderOverride sets the "header_override" field.
func (u *ChannelKeyUpsertOne) SetHeaderOverride(v map[string]string) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetHeaderOverride(v)
	})
}

// UpdateHeaderOverride sets the "header_override" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateHeaderOverride() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateHeaderOverride()
	})
}

// ClearHeaderOverride clears the value of the "header_override" field.
func (u *ChannelKeyUpsertOne) ClearHeaderOverride() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearHeaderOverride()
	})
}

// SetStatus sets the "status" field.
func (u *ChannelKeyUpsertOne) SetStatus(v channelkey.Status) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateStatus() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorMsg sets the "error_msg" field.
func (u *ChannelKeyUpsertOne) SetErrorMsg(v string) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetErrorMsg(v)
	})
}

// UpdateErrorMsg sets the "error_msg" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateErrorMsg() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateErrorMsg()
	})
}

// SetPriority sets the "priority" field.
func (u *ChannelKeyUpsertOne) SetPriority(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *ChannelKeyUpsertOne) AddPriority(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdatePriority() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdatePriority()
	})
}

// SetWeight sets the "weight" field.
func (u *ChannelKeyUpsertOne) SetWeight(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *ChannelKeyUpsertOne) AddWeight(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateWeight() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateWeight()
	})
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *ChannelKeyUpsertOne) SetMaxConcurrency(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetMaxConcurrency(v)
	})
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *ChannelKeyUpsertOne) AddMaxConcurrency(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddMaxConcurrency(v)
	})
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateMaxConcurrency() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateMaxConcurrency()
	})
}

// SetMaxRpm sets the "max_rpm" field.
func (u *ChannelKeyUpsertOne) SetMaxRpm(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetMaxRpm(v)
	})
}

// AddMaxRpm adds v to the "max_rpm" field.
func (u *ChannelKeyUpsertOne) AddMaxRpm(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddMaxRpm(v)
	})
}

// UpdateMaxRpm sets the "max_rpm" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateMaxRpm() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateMaxRpm()
	})
}

// SetCostRatio sets the "cost_ratio" field.
func (u *ChannelKeyUpsertOne) SetCostRatio(v float64) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetCostRatio(v)
	})
}

// AddCostRatio adds v to the "cost_ratio" field.
func (u *ChannelKeyUpsertOne) AddCostRatio(v float64) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddCostRatio(v)
	})
}

// UpdateCostRatio sets the "cost_ratio" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateCostRatio() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateCostRatio()
	})
}

// SetTags sets the "tags" field.
func (u *ChannelKeyUpsertOne) SetTags(v []string) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateTags() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *ChannelKeyUpsertOne) ClearTags() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearTags()
	})
}

// SetTestModel sets the "test_model" field.
func (u *ChannelKeyUpsertOne) SetTestModel(v string) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetTestModel(v)
	})
}

// UpdateTestModel sets the "test_model" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateTestModel() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateTestModel()
	})
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (u *ChannelKeyUpsertOne) SetResponseTimeMs(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetResponseTimeMs(v)
	})
}

// AddResponseTimeMs adds v to the "response_time_ms" field.
func (u *ChannelKeyUpsertOne) AddResponseTimeMs(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddResponseTimeMs(v)
	})
}

// UpdateResponseTimeMs sets the "response_time_ms" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateResponseTimeMs() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateResponseTimeMs()
	})
}

// SetTestedAt sets the "tested_at" field.
func (u *ChannelKeyUpsertOne) SetTestedAt(v time.Time) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetTestedAt(v)
	})
}

// UpdateTestedAt sets the "tested_at" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateTestedAt() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateTestedAt()
	})
}

// ClearTestedAt clears the value of the "tested_at" field.
func (u *ChannelKeyUpsertOne) ClearTestedAt() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearTestedAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *ChannelKeyUpsertOne) SetLastUsedAt(v time.Time) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateLastUsedAt() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *ChannelKeyUpsertOne) ClearLastUsedAt() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetBalance sets the "balance" field.
func (u *ChannelKeyUpsertOne) SetBalance(v float64) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *ChannelKeyUpsertOne) AddBalance(v float64) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateBalance() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateBalance()
	})
}

// SetBalanceUpdatedAt sets the "balance_updated_at" field.
func (u *ChannelKeyUpsertOne) SetBalanceUpdatedAt(v time.Time) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetBalanceUpdatedAt(v)
	})
}

// UpdateBalanceUpdatedAt sets the "balance_updated_at" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateBalanceUpdatedAt() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateBalanceUpdatedAt()
	})
}

// ClearBalanceUpdatedAt clears the value of the "balance_updated_at" field.
func (u *ChannelKeyUpsertOne) ClearBalanceUpdatedAt() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearBalanceUpdatedAt()
	})
}

// SetBalanceCheckEnabled sets the "balance_check_enabled" field.
func (u *ChannelKeyUpsertOne) SetBalanceCheckEnabled(v bool) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetBalanceCheckEnabled(v)
	})
}

// UpdateBalanceCheckEnabled sets the "balance_check_enabled" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateBalanceCheckEnabled() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateBalanceCheckEnabled()
	})
}

// SetProbeEnabled sets the "probe_enabled" field.
func (u *ChannelKeyUpsertOne) SetProbeEnabled(v bool) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetProbeEnabled(v)
	})
}

// UpdateProbeEnabled sets the "probe_enabled" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateProbeEnabled() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateProbeEnabled()
	})
}

// SetProbeModel sets the "probe_model" field.
func (u *ChannelKeyUpsertOne) SetProbeModel(v string) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetProbeModel(v)
	})
}

// UpdateProbeModel sets the "probe_model" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateProbeModel() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateProbeModel()
	})
}

// SetHealthStatus sets the "health_status" field.
func (u *ChannelKeyUpsertOne) SetHealthStatus(v channelkey.HealthStatus) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetHealthStatus(v)
	})
}

// UpdateHealthStatus sets the "health_status" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateHealthStatus() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateHealthStatus()
	})
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (u *ChannelKeyUpsertOne) SetConsecutiveFailures(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetConsecutiveFailures(v)
	})
}

// AddConsecutiveFailures adds v to the "consecutive_failures" field.
func (u *ChannelKeyUpsertOne) AddConsecutiveFailures(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddConsecutiveFailures(v)
	})
}

// UpdateConsecutiveFailures sets the "consecutive_failures" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateConsecutiveFailures() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateConsecutiveFailures()
	})
}

// SetConsecutiveSuccesses sets the "consecutive_successes" field.
func (u *ChannelKeyUpsertOne) SetConsecutiveSuccesses(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetConsecutiveSuccesses(v)
	})
}

// AddConsecutiveSuccesses adds v to the "consecutive_successes" field.
func (u *ChannelKeyUpsertOne) AddConsecutiveSuccesses(v int) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddConsecutiveSuccesses(v)
	})
}

// UpdateConsecutiveSuccesses sets the "consecutive_successes" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateConsecutiveSuccesses() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateConsecutiveSuccesses()
	})
}

// SetLastProbeAt sets the "last_probe_at" field.
func (u *ChannelKeyUpsertOne) SetLastProbeAt(v time.Time) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetLastProbeAt(v)
	})
}

// UpdateLastProbeAt sets the "last_probe_at" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateLastProbeAt() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateLastProbeAt()
	})
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (u *ChannelKeyUpsertOne) ClearLastProbeAt() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearLastProbeAt()
	})
}

// SetUpstreamRateEnabled sets the "upstream_rate_enabled" field.
func (u *ChannelKeyUpsertOne) SetUpstreamRateEnabled(v bool) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetUpstreamRateEnabled(v)
	})
}

// UpdateUpstreamRateEnabled sets the "upstream_rate_enabled" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateUpstreamRateEnabled() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateUpstreamRateEnabled()
	})
}

// SetUpstreamRatePath sets the "upstream_rate_path" field.
func (u *ChannelKeyUpsertOne) SetUpstreamRatePath(v string) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetUpstreamRatePath(v)
	})
}

// UpdateUpstreamRatePath sets the "upstream_rate_path" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateUpstreamRatePath() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateUpstreamRatePath()
	})
}

// SetUseUpstreamRateForCost sets the "use_upstream_rate_for_cost" field.
func (u *ChannelKeyUpsertOne) SetUseUpstreamRateForCost(v bool) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetUseUpstreamRateForCost(v)
	})
}

// UpdateUseUpstreamRateForCost sets the "use_upstream_rate_for_cost" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateUseUpstreamRateForCost() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateUseUpstreamRateForCost()
	})
}

// SetUpstreamRate sets the "upstream_rate" field.
func (u *ChannelKeyUpsertOne) SetUpstreamRate(v float64) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetUpstreamRate(v)
	})
}

// AddUpstreamRate adds v to the "upstream_rate" field.
func (u *ChannelKeyUpsertOne) AddUpstreamRate(v float64) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddUpstreamRate(v)
	})
}

// UpdateUpstreamRate sets the "upstream_rate" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateUpstreamRate() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateUpstreamRate()
	})
}

// SetUpstreamRateAt sets the "upstream_rate_at" field.
func (u *ChannelKeyUpsertOne) SetUpstreamRateAt(v time.Time) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetUpstreamRateAt(v)
	})
}

// UpdateUpstreamRateAt sets the "upstream_rate_at" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateUpstreamRateAt() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateUpstreamRateAt()
	})
}

// ClearUpstreamRateAt clears the value of the "upstream_rate_at" field.
func (u *ChannelKeyUpsertOne) ClearUpstreamRateAt() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearUpstreamRateAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelKeyUpsertOne) SetUpdatedAt(v time.Time) *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelKeyUpsertOne) UpdateUpdatedAt() *ChannelKeyUpsertOne {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChannelKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelKeyUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelKeyUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelKeyCreateBulk is the builder for creating many ChannelKey entities in bulk.
type ChannelKeyCreateBulk struct {
	config
	err      error
	builders []*ChannelKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the ChannelKey entities in the database.
func (ckcb *ChannelKeyCreateBulk) Save(ctx context.Context) ([]*ChannelKey, error) {
	if ckcb.err != nil {
		return nil, ckcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ckcb.builders))
	nodes := make([]*ChannelKey, len(ckcb.builders))
	mutators := make([]Mutator, len(ckcb.builders))
	for i := range ckcb.builders {
		func(i int, root context.Context) {
			builder := ckcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ckcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ckcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ckcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ckcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ckcb *ChannelKeyCreateBulk) SaveX(ctx context.Context) []*ChannelKey {
	v, err := ckcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ckcb *ChannelKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := ckcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ckcb *ChannelKeyCreateBulk) ExecX(ctx context.Context) {
	if err := ckcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelKeyUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (ckcb *ChannelKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelKeyUpsertBulk {
	ckcb.conflict = opts
	return &ChannelKeyUpsertBulk{
		create: ckcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ckcb *ChannelKeyCreateBulk) OnConflictColumns(columns ...string) *ChannelKeyUpsertBulk {
	ckcb.conflict = append(ckcb.conflict, sql.ConflictColumns(columns...))
	return &ChannelKeyUpsertBulk{
		create: ckcb,
	}
}

// ChannelKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of ChannelKey nodes.
type ChannelKeyUpsertBulk struct {
	create *ChannelKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChannelKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelKeyUpsertBulk) UpdateNewValues() *ChannelKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(channelkey.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelKeyUpsertBulk) Ignore() *ChannelKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelKeyUpsertBulk) DoNothing() *ChannelKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelKeyCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelKeyUpsertBulk) Update(set func(*ChannelKeyUpsert)) *ChannelKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ChannelKeyUpsertBulk) SetName(v string) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateName() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *ChannelKeyUpsertBulk) SetType(v channelkey.Type) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateType() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateType()
	})
}

// SetAPIKey sets the "api_key" field.
func (u *ChannelKeyUpsertBulk) SetAPIKey(v string) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetAPIKey(v)
	})
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateAPIKey() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateAPIKey()
	})
}

// SetModels sets the "models" field.
func (u *ChannelKeyUpsertBulk) SetModels(v []string) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetModels(v)
	})
}

// UpdateModels sets the "models" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateModels() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateModels()
	})
}

// SetModelMapping sets the "model_mapping" field.
func (u *ChannelKeyUpsertBulk) SetModelMapping(v map[string]string) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetModelMapping(v)
	})
}

// UpdateModelMapping sets the "model_mapping" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateModelMapping() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateModelMapping()
	})
}

// ClearModelMapping clears the value of the "model_mapping" field.
func (u *ChannelKeyUpsertBulk) ClearModelMapping() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearModelMapping()
	})
}

// SetParamOverride sets the "param_override" field.
func (u *ChannelKeyUpsertBulk) SetParamOverride(v map[string]interface{}) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetParamOverride(v)
	})
}

// UpdateParamOverride sets the "param_override" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateParamOverride() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateParamOverride()
	})
}

// ClearParamOverride clears the value of the "param_override" field.
func (u *ChannelKeyUpsertBulk) ClearParamOverride() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearParamOverride()
	})
}

// SetHeaderOverride sets the "header_override" field.
func (u *ChannelKeyUpsertBulk) SetHeaderOverride(v map[string]string) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetHeaderOverride(v)
	})
}

// UpdateHeaderOverride sets the "header_override" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateHeaderOverride() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateHeaderOverride()
	})
}

// ClearHeaderOverride clears the value of the "header_override" field.
func (u *ChannelKeyUpsertBulk) ClearHeaderOverride() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearHeaderOverride()
	})
}

// SetStatus sets the "status" field.
func (u *ChannelKeyUpsertBulk) SetStatus(v channelkey.Status) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateStatus() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorMsg sets the "error_msg" field.
func (u *ChannelKeyUpsertBulk) SetErrorMsg(v string) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetErrorMsg(v)
	})
}

// UpdateErrorMsg sets the "error_msg" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateErrorMsg() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateErrorMsg()
	})
}

// SetPriority sets the "priority" field.
func (u *ChannelKeyUpsertBulk) SetPriority(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *ChannelKeyUpsertBulk) AddPriority(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdatePriority() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdatePriority()
	})
}

// SetWeight sets the "weight" field.
func (u *ChannelKeyUpsertBulk) SetWeight(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *ChannelKeyUpsertBulk) AddWeight(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateWeight() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateWeight()
	})
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *ChannelKeyUpsertBulk) SetMaxConcurrency(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetMaxConcurrency(v)
	})
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *ChannelKeyUpsertBulk) AddMaxConcurrency(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddMaxConcurrency(v)
	})
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateMaxConcurrency() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateMaxConcurrency()
	})
}

// SetMaxRpm sets the "max_rpm" field.
func (u *ChannelKeyUpsertBulk) SetMaxRpm(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetMaxRpm(v)
	})
}

// AddMaxRpm adds v to the "max_rpm" field.
func (u *ChannelKeyUpsertBulk) AddMaxRpm(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddMaxRpm(v)
	})
}

// UpdateMaxRpm sets the "max_rpm" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateMaxRpm() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateMaxRpm()
	})
}

// SetCostRatio sets the "cost_ratio" field.
func (u *ChannelKeyUpsertBulk) SetCostRatio(v float64) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetCostRatio(v)
	})
}

// AddCostRatio adds v to the "cost_ratio" field.
func (u *ChannelKeyUpsertBulk) AddCostRatio(v float64) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddCostRatio(v)
	})
}

// UpdateCostRatio sets the "cost_ratio" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateCostRatio() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateCostRatio()
	})
}

// SetTags sets the "tags" field.
func (u *ChannelKeyUpsertBulk) SetTags(v []string) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateTags() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *ChannelKeyUpsertBulk) ClearTags() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearTags()
	})
}

// SetTestModel sets the "test_model" field.
func (u *ChannelKeyUpsertBulk) SetTestModel(v string) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetTestModel(v)
	})
}

// UpdateTestModel sets the "test_model" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateTestModel() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateTestModel()
	})
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (u *ChannelKeyUpsertBulk) SetResponseTimeMs(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetResponseTimeMs(v)
	})
}

// AddResponseTimeMs adds v to the "response_time_ms" field.
func (u *ChannelKeyUpsertBulk) AddResponseTimeMs(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddResponseTimeMs(v)
	})
}

// UpdateResponseTimeMs sets the "response_time_ms" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateResponseTimeMs() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateResponseTimeMs()
	})
}

// SetTestedAt sets the "tested_at" field.
func (u *ChannelKeyUpsertBulk) SetTestedAt(v time.Time) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetTestedAt(v)
	})
}

// UpdateTestedAt sets the "tested_at" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateTestedAt() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateTestedAt()
	})
}

// ClearTestedAt clears the value of the "tested_at" field.
func (u *ChannelKeyUpsertBulk) ClearTestedAt() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearTestedAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *ChannelKeyUpsertBulk) SetLastUsedAt(v time.Time) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateLastUsedAt() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *ChannelKeyUpsertBulk) ClearLastUsedAt() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetBalance sets the "balance" field.
func (u *ChannelKeyUpsertBulk) SetBalance(v float64) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *ChannelKeyUpsertBulk) AddBalance(v float64) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateBalance() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateBalance()
	})
}

// SetBalanceUpdatedAt sets the "balance_updated_at" field.
func (u *ChannelKeyUpsertBulk) SetBalanceUpdatedAt(v time.Time) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetBalanceUpdatedAt(v)
	})
}

// UpdateBalanceUpdatedAt sets the "balance_updated_at" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateBalanceUpdatedAt() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateBalanceUpdatedAt()
	})
}

// ClearBalanceUpdatedAt clears the value of the "balance_updated_at" field.
func (u *ChannelKeyUpsertBulk) ClearBalanceUpdatedAt() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearBalanceUpdatedAt()
	})
}

// SetBalanceCheckEnabled sets the "balance_check_enabled" field.
func (u *ChannelKeyUpsertBulk) SetBalanceCheckEnabled(v bool) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetBalanceCheckEnabled(v)
	})
}

// UpdateBalanceCheckEnabled sets the "balance_check_enabled" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateBalanceCheckEnabled() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateBalanceCheckEnabled()
	})
}

// SetProbeEnabled sets the "probe_enabled" field.
func (u *ChannelKeyUpsertBulk) SetProbeEnabled(v bool) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetProbeEnabled(v)
	})
}

// UpdateProbeEnabled sets the "probe_enabled" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateProbeEnabled() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateProbeEnabled()
	})
}

// SetProbeModel sets the "probe_model" field.
func (u *ChannelKeyUpsertBulk) SetProbeModel(v string) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetProbeModel(v)
	})
}

// UpdateProbeModel sets the "probe_model" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateProbeModel() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateProbeModel()
	})
}

// SetHealthStatus sets the "health_status" field.
func (u *ChannelKeyUpsertBulk) SetHealthStatus(v channelkey.HealthStatus) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetHealthStatus(v)
	})
}

// UpdateHealthStatus sets the "health_status" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateHealthStatus() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateHealthStatus()
	})
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (u *ChannelKeyUpsertBulk) SetConsecutiveFailures(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetConsecutiveFailures(v)
	})
}

// AddConsecutiveFailures adds v to the "consecutive_failures" field.
func (u *ChannelKeyUpsertBulk) AddConsecutiveFailures(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddConsecutiveFailures(v)
	})
}

// UpdateConsecutiveFailures sets the "consecutive_failures" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateConsecutiveFailures() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateConsecutiveFailures()
	})
}

// SetConsecutiveSuccesses sets the "consecutive_successes" field.
func (u *ChannelKeyUpsertBulk) SetConsecutiveSuccesses(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetConsecutiveSuccesses(v)
	})
}

// AddConsecutiveSuccesses adds v to the "consecutive_successes" field.
func (u *ChannelKeyUpsertBulk) AddConsecutiveSuccesses(v int) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddConsecutiveSuccesses(v)
	})
}

// UpdateConsecutiveSuccesses sets the "consecutive_successes" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateConsecutiveSuccesses() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateConsecutiveSuccesses()
	})
}

// SetLastProbeAt sets the "last_probe_at" field.
func (u *ChannelKeyUpsertBulk) SetLastProbeAt(v time.Time) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetLastProbeAt(v)
	})
}

// UpdateLastProbeAt sets the "last_probe_at" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateLastProbeAt() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateLastProbeAt()
	})
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (u *ChannelKeyUpsertBulk) ClearLastProbeAt() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearLastProbeAt()
	})
}

// SetUpstreamRateEnabled sets the "upstream_rate_enabled" field.
func (u *ChannelKeyUpsertBulk) SetUpstreamRateEnabled(v bool) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetUpstreamRateEnabled(v)
	})
}

// UpdateUpstreamRateEnabled sets the "upstream_rate_enabled" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateUpstreamRateEnabled() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateUpstreamRateEnabled()
	})
}

// SetUpstreamRatePath sets the "upstream_rate_path" field.
func (u *ChannelKeyUpsertBulk) SetUpstreamRatePath(v string) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetUpstreamRatePath(v)
	})
}

// UpdateUpstreamRatePath sets the "upstream_rate_path" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateUpstreamRatePath() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateUpstreamRatePath()
	})
}

// SetUseUpstreamRateForCost sets the "use_upstream_rate_for_cost" field.
func (u *ChannelKeyUpsertBulk) SetUseUpstreamRateForCost(v bool) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetUseUpstreamRateForCost(v)
	})
}

// UpdateUseUpstreamRateForCost sets the "use_upstream_rate_for_cost" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateUseUpstreamRateForCost() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateUseUpstreamRateForCost()
	})
}

// SetUpstreamRate sets the "upstream_rate" field.
func (u *ChannelKeyUpsertBulk) SetUpstreamRate(v float64) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetUpstreamRate(v)
	})
}

// AddUpstreamRate adds v to the "upstream_rate" field.
func (u *ChannelKeyUpsertBulk) AddUpstreamRate(v float64) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.AddUpstreamRate(v)
	})
}

// UpdateUpstreamRate sets the "upstream_rate" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateUpstreamRate() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateUpstreamRate()
	})
}

// SetUpstreamRateAt sets the "upstream_rate_at" field.
func (u *ChannelKeyUpsertBulk) SetUpstreamRateAt(v time.Time) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetUpstreamRateAt(v)
	})
}

// UpdateUpstreamRateAt sets the "upstream_rate_at" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateUpstreamRateAt() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateUpstreamRateAt()
	})
}

// ClearUpstreamRateAt clears the value of the "upstream_rate_at" field.
func (u *ChannelKeyUpsertBulk) ClearUpstreamRateAt() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.ClearUpstreamRateAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelKeyUpsertBulk) SetUpdatedAt(v time.Time) *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelKeyUpsertBulk) UpdateUpdatedAt() *ChannelKeyUpsertBulk {
	return u.Update(func(s *ChannelKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChannelKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
