// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/channelcredential"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ChannelCredentialDelete is the builder for deleting a ChannelCredential entity.
type ChannelCredentialDelete struct {
	config
	hooks    []Hook
	mutation *ChannelCredentialMutation
}

// Where appends a list predicates to the ChannelCredentialDelete builder.
func (ccd *ChannelCredentialDelete) Where(ps ...predicate.ChannelCredential) *ChannelCredentialDelete {
	ccd.mutation.Where(ps...)
	return ccd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ccd *ChannelCredentialDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ccd.sqlExec, ccd.mutation, ccd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ccd *ChannelCredentialDelete) ExecX(ctx context.Context) int {
	n, err := ccd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ccd *ChannelCredentialDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(channelcredential.Table, sqlgraph.NewFieldSpec(channelcredential.FieldID, field.TypeInt))
	if ps := ccd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ccd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ccd.mutation.done = true
	return affected, err
}

// ChannelCredentialDeleteOne is the builder for deleting a single ChannelCredential entity.
type ChannelCredentialDeleteOne struct {
	ccd *ChannelCredentialDelete
}

// Where appends a list predicates to the ChannelCredentialDelete builder.
func (ccdo *ChannelCredentialDeleteOne) Where(ps ...predicate.ChannelCredential) *ChannelCredentialDeleteOne {
	ccdo.ccd.mutation.Where(ps...)
	return ccdo
}

// Exec executes the deletion query.
func (ccdo *ChannelCredentialDeleteOne) Exec(ctx context.Context) error {
	n, err := ccdo.ccd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{channelcredential.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ccdo *ChannelCredentialDeleteOne) ExecX(ctx context.Context) {
	if err := ccdo.Exec(ctx); err != nil {
		panic(err)
	}
}
