// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/inviterebatelog"
)

// InviteRebateLog is the model entity for the InviteRebateLog schema.
type InviteRebateLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 流水归属人（邀请人）用户 ID
	UserID int `json:"user_id,omitempty"`
	// Action holds the value of the "action" field.
	Action inviterebatelog.Action `json:"action,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// accrue：触发本次计提的下线（被邀请人）用户 ID
	SourceUserID *int `json:"source_user_id,omitempty"`
	// accrue：触发本次计提的充值订单号
	SourceOrderNo *string `json:"source_order_no,omitempty"`
	// transfer：转入余额后的用户余额快照，仅审计用
	BalanceAfter *float64 `json:"balance_after,omitempty"`
	// 幂等键：accrue 为 invite-accrue:<订单号>，transfer 为 invite-transfer:<流水ID>；NULL 表示无幂等要求
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InviteRebateLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case inviterebatelog.FieldAmount, inviterebatelog.FieldBalanceAfter:
			values[i] = new(sql.NullFloat64)
		case inviterebatelog.FieldID, inviterebatelog.FieldUserID, inviterebatelog.FieldSourceUserID:
			values[i] = new(sql.NullInt64)
		case inviterebatelog.FieldAction, inviterebatelog.FieldSourceOrderNo, inviterebatelog.FieldIdempotencyKey:
			values[i] = new(sql.NullString)
		case inviterebatelog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InviteRebateLog fields.
func (irl *InviteRebateLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case inviterebatelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			irl.ID = int(value.Int64)
		case inviterebatelog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				irl.UserID = int(value.Int64)
			}
		case inviterebatelog.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				irl.Action = inviterebatelog.Action(value.String)
			}
		case inviterebatelog.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				irl.Amount = value.Float64
			}
		case inviterebatelog.FieldSourceUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_user_id", values[i])
			} else if value.Valid {
				irl.SourceUserID = new(int)
				*irl.SourceUserID = int(value.Int64)
			}
		case inviterebatelog.FieldSourceOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_order_no", values[i])
			} else if value.Valid {
				irl.SourceOrderNo = new(string)
				*irl.SourceOrderNo = value.String
			}
		case inviterebatelog.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				irl.BalanceAfter = new(float64)
				*irl.BalanceAfter = value.Float64
			}
		case inviterebatelog.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				irl.IdempotencyKey = new(string)
				*irl.IdempotencyKey = value.String
			}
		case inviterebatelog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				irl.CreatedAt = value.Time
			}
		default:
			irl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InviteRebateLog.
// This includes values selected through modifiers, order, etc.
func (irl *InviteRebateLog) Value(name string) (ent.Value, error) {
	return irl.selectValues.Get(name)
}

// Update returns a builder for updating this InviteRebateLog.
// Note that you need to call InviteRebateLog.Unwrap() before calling this method if this InviteRebateLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (irl *InviteRebateLog) Update() *InviteRebateLogUpdateOne {
	return NewInviteRebateLogClient(irl.config).UpdateOne(irl)
}

// Unwrap unwraps the InviteRebateLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (irl *InviteRebateLog) Unwrap() *InviteRebateLog {
	_tx, ok := irl.config.driver.(*txDriver)
	if !ok {
		panic("ent: InviteRebateLog is not a transactional entity")
	}
	irl.config.driver = _tx.drv
	return irl
}

// String implements the fmt.Stringer.
func (irl *InviteRebateLog) String() string {
	var builder strings.Builder
	builder.WriteString("InviteRebateLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", irl.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", irl.UserID))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(fmt.Sprintf("%v", irl.Action))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", irl.Amount))
	builder.WriteString(", ")
	if v := irl.SourceUserID; v != nil {
		builder.WriteString("source_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := irl.SourceOrderNo; v != nil {
		builder.WriteString("source_order_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := irl.BalanceAfter; v != nil {
		builder.WriteString("balance_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := irl.IdempotencyKey; v != nil {
		builder.WriteString("idempotency_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(irl.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InviteRebateLogs is a parsable slice of InviteRebateLog.
type InviteRebateLogs []*InviteRebateLog
