// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/modelprice"
	"github.com/DouDOU-start/airgate-core/ent/modeltag"
)

// ModelTagCreate is the builder for creating a ModelTag entity.
type ModelTagCreate struct {
	config
	mutation *ModelTagMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (mtc *ModelTagCreate) SetName(s string) *ModelTagCreate {
	mtc.mutation.SetName(s)
	return mtc
}

// SetCreatedAt sets the "created_at" field.
func (mtc *ModelTagCreate) SetCreatedAt(t time.Time) *ModelTagCreate {
	mtc.mutation.SetCreatedAt(t)
	return mtc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mtc *ModelTagCreate) SetNillableCreatedAt(t *time.Time) *ModelTagCreate {
	if t != nil {
		mtc.SetCreatedAt(*t)
	}
	return mtc
}

// SetUpdatedAt sets the "updated_at" field.
func (mtc *ModelTagCreate) SetUpdatedAt(t time.Time) *ModelTagCreate {
	mtc.mutation.SetUpdatedAt(t)
	return mtc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mtc *ModelTagCreate) SetNillableUpdatedAt(t *time.Time) *ModelTagCreate {
	if t != nil {
		mtc.SetUpdatedAt(*t)
	}
	return mtc
}

// AddPriceIDs adds the "prices" edge to the ModelPrice entity by IDs.
func (mtc *ModelTagCreate) AddPriceIDs(ids ...int) *ModelTagCreate {
	mtc.mutation.AddPriceIDs(ids...)
	return mtc
}

// AddPrices adds the "prices" edges to the ModelPrice entity.
func (mtc *ModelTagCreate) AddPrices(m ...*ModelPrice) *ModelTagCreate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mtc.AddPriceIDs(ids...)
}

// Mutation returns the ModelTagMutation object of the builder.
func (mtc *ModelTagCreate) Mutation() *ModelTagMutation {
	return mtc.mutation
}

// Save creates the ModelTag in the database.
func (mtc *ModelTagCreate) Save(ctx context.Context) (*ModelTag, error) {
	mtc.defaults()
	return withHooks(ctx, mtc.sqlSave, mtc.mutation, mtc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mtc *ModelTagCreate) SaveX(ctx context.Context) *ModelTag {
	v, err := mtc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mtc *ModelTagCreate) Exec(ctx context.Context) error {
	_, err := mtc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtc *ModelTagCreate) ExecX(ctx context.Context) {
	if err := mtc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mtc *ModelTagCreate) defaults() {
	if _, ok := mtc.mutation.CreatedAt(); !ok {
		v := modeltag.DefaultCreatedAt()
		mtc.mutation.SetCreatedAt(v)
	}
	if _, ok := mtc.mutation.UpdatedAt(); !ok {
		v := modeltag.DefaultUpdatedAt()
		mtc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mtc *ModelTagCreate) check() error {
	if _, ok := mtc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ModelTag.name"`)}
	}
	if v, ok := mtc.mutation.Name(); ok {
		if err := modeltag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ModelTag.name": %w`, err)}
		}
	}
	if _, ok := mtc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelTag.created_at"`)}
	}
	if _, ok := mtc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelTag.updated_at"`)}
	}
	return nil
}

func (mtc *ModelTagCreate) sqlSave(ctx context.Context) (*ModelTag, error) {
	if err := mtc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mtc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mtc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mtc.mutation.id = &_node.ID
	mtc.mutation.done = true
	return _node, nil
}

func (mtc *ModelTagCreate) createSpec() (*ModelTag, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelTag{config: mtc.config}
		_spec = sqlgraph.NewCreateSpec(modeltag.Table, sqlgraph.NewFieldSpec(modeltag.FieldID, field.TypeInt))
	)
	_spec.OnConflict = mtc.conflict
	if value, ok := mtc.mutation.Name(); ok {
		_spec.SetField(modeltag.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := mtc.mutation.CreatedAt(); ok {
		_spec.SetField(modeltag.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mtc.mutation.UpdatedAt(); ok {
		_spec.SetField(modeltag.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := mtc.mutation.PricesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modeltag.PricesTable,
			Columns: []string{modeltag.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelprice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelTag.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelTagUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (mtc *ModelTagCreate) OnConflict(opts ...sql.ConflictOption) *ModelTagUpsertOne {
	mtc.conflict = opts
	return &ModelTagUpsertOne{
		create: mtc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mtc *ModelTagCreate) OnConflictColumns(columns ...string) *ModelTagUpsertOne {
	mtc.conflict = append(mtc.conflict, sql.ConflictColumns(columns...))
	return &ModelTagUpsertOne{
		create: mtc,
	}
}

type (
	// ModelTagUpsertOne is the builder for "upsert"-ing
	//  one ModelTag node.
	ModelTagUpsertOne struct {
		create *ModelTagCreate
	}

	// ModelTagUpsert is the "OnConflict" setter.
	ModelTagUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ModelTagUpsert) SetName(v string) *ModelTagUpsert {
	u.Set(modeltag.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ModelTagUpsert) UpdateName() *ModelTagUpsert {
	u.SetExcluded(modeltag.FieldName)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelTagUpsert) SetUpdatedAt(v time.Time) *ModelTagUpsert {
	u.Set(modeltag.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelTagUpsert) UpdateUpdatedAt() *ModelTagUpsert {
	u.SetExcluded(modeltag.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelTagUpsertOne) UpdateNewValues() *ModelTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modeltag.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelTag.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelTagUpsertOne) Ignore() *ModelTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelTagUpsertOne) DoNothing() *ModelTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelTagCreate.OnConflict
// documentation for more info.
func (u *ModelTagUpsertOne) Update(set func(*ModelTagUpsert)) *ModelTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ModelTagUpsertOne) SetName(v string) *ModelTagUpsertOne {
	return u.Update(func(s *ModelTagUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ModelTagUpsertOne) UpdateName() *ModelTagUpsertOne {
	return u.Update(func(s *ModelTagUpsert) {
		s.UpdateName()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelTagUpsertOne) SetUpdatedAt(v time.Time) *ModelTagUpsertOne {
	return u.Update(func(s *ModelTagUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelTagUpsertOne) UpdateUpdatedAt() *ModelTagUpsertOne {
	return u.Update(func(s *ModelTagUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ModelTagUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelTagCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelTagUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelTagUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelTagUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelTagCreateBulk is the builder for creating many ModelTag entities in bulk.
type ModelTagCreateBulk struct {
	config
	err      error
	builders []*ModelTagCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelTag entities in the database.
func (mtcb *ModelTagCreateBulk) Save(ctx context.Context) ([]*ModelTag, error) {
	if mtcb.err != nil {
		return nil, mtcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mtcb.builders))
	nodes := make([]*ModelTag, len(mtcb.builders))
	mutators := make([]Mutator, len(mtcb.builders))
	for i := range mtcb.builders {
		func(i int, root context.Context) {
			builder := mtcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mtcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mtcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mtcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mtcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mtcb *ModelTagCreateBulk) SaveX(ctx context.Context) []*ModelTag {
	v, err := mtcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mtcb *ModelTagCreateBulk) Exec(ctx context.Context) error {
	_, err := mtcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtcb *ModelTagCreateBulk) ExecX(ctx context.Context) {
	if err := mtcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelTag.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelTagUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (mtcb *ModelTagCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelTagUpsertBulk {
	mtcb.conflict = opts
	return &ModelTagUpsertBulk{
		create: mtcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mtcb *ModelTagCreateBulk) OnConflictColumns(columns ...string) *ModelTagUpsertBulk {
	mtcb.conflict = append(mtcb.conflict, sql.ConflictColumns(columns...))
	return &ModelTagUpsertBulk{
		create: mtcb,
	}
}

// ModelTagUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelTag nodes.
type ModelTagUpsertBulk struct {
	create *ModelTagCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelTagUpsertBulk) UpdateNewValues() *ModelTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modeltag.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelTag.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelTagUpsertBulk) Ignore() *ModelTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelTagUpsertBulk) DoNothing() *ModelTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelTagCreateBulk.OnConflict
// documentation for more info.
func (u *ModelTagUpsertBulk) Update(set func(*ModelTagUpsert)) *ModelTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ModelTagUpsertBulk) SetName(v string) *ModelTagUpsertBulk {
	return u.Update(func(s *ModelTagUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ModelTagUpsertBulk) UpdateName() *ModelTagUpsertBulk {
	return u.Update(func(s *ModelTagUpsert) {
		s.UpdateName()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelTagUpsertBulk) SetUpdatedAt(v time.Time) *ModelTagUpsertBulk {
	return u.Update(func(s *ModelTagUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelTagUpsertBulk) UpdateUpdatedAt() *ModelTagUpsertBulk {
	return u.Update(func(s *ModelTagUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ModelTagUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelTagCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelTagCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelTagUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
