// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/oauthclient"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// OAuthClientUpdate is the builder for updating OAuthClient entities.
type OAuthClientUpdate struct {
	config
	hooks     []Hook
	mutation  *OAuthClientMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OAuthClientUpdate builder.
func (ocu *OAuthClientUpdate) Where(ps ...predicate.OAuthClient) *OAuthClientUpdate {
	ocu.mutation.Where(ps...)
	return ocu
}

// SetSecretHash sets the "secret_hash" field.
func (ocu *OAuthClientUpdate) SetSecretHash(s string) *OAuthClientUpdate {
	ocu.mutation.SetSecretHash(s)
	return ocu
}

// SetNillableSecretHash sets the "secret_hash" field if the given value is not nil.
func (ocu *OAuthClientUpdate) SetNillableSecretHash(s *string) *OAuthClientUpdate {
	if s != nil {
		ocu.SetSecretHash(*s)
	}
	return ocu
}

// SetSecretHint sets the "secret_hint" field.
func (ocu *OAuthClientUpdate) SetSecretHint(s string) *OAuthClientUpdate {
	ocu.mutation.SetSecretHint(s)
	return ocu
}

// SetNillableSecretHint sets the "secret_hint" field if the given value is not nil.
func (ocu *OAuthClientUpdate) SetNillableSecretHint(s *string) *OAuthClientUpdate {
	if s != nil {
		ocu.SetSecretHint(*s)
	}
	return ocu
}

// SetName sets the "name" field.
func (ocu *OAuthClientUpdate) SetName(s string) *OAuthClientUpdate {
	ocu.mutation.SetName(s)
	return ocu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ocu *OAuthClientUpdate) SetNillableName(s *string) *OAuthClientUpdate {
	if s != nil {
		ocu.SetName(*s)
	}
	return ocu
}

// SetDescription sets the "description" field.
func (ocu *OAuthClientUpdate) SetDescription(s string) *OAuthClientUpdate {
	ocu.mutation.SetDescription(s)
	return ocu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ocu *OAuthClientUpdate) SetNillableDescription(s *string) *OAuthClientUpdate {
	if s != nil {
		ocu.SetDescription(*s)
	}
	return ocu
}

// SetRedirectUris sets the "redirect_uris" field.
func (ocu *OAuthClientUpdate) SetRedirectUris(s []string) *OAuthClientUpdate {
	ocu.mutation.SetRedirectUris(s)
	return ocu
}

// AppendRedirectUris appends s to the "redirect_uris" field.
func (ocu *OAuthClientUpdate) AppendRedirectUris(s []string) *OAuthClientUpdate {
	ocu.mutation.AppendRedirectUris(s)
	return ocu
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (ocu *OAuthClientUpdate) SetAllowedScopes(s []string) *OAuthClientUpdate {
	ocu.mutation.SetAllowedScopes(s)
	return ocu
}

// AppendAllowedScopes appends s to the "allowed_scopes" field.
func (ocu *OAuthClientUpdate) AppendAllowedScopes(s []string) *OAuthClientUpdate {
	ocu.mutation.AppendAllowedScopes(s)
	return ocu
}

// SetFirstParty sets the "first_party" field.
func (ocu *OAuthClientUpdate) SetFirstParty(b bool) *OAuthClientUpdate {
	ocu.mutation.SetFirstParty(b)
	return ocu
}

// SetNillableFirstParty sets the "first_party" field if the given value is not nil.
func (ocu *OAuthClientUpdate) SetNillableFirstParty(b *bool) *OAuthClientUpdate {
	if b != nil {
		ocu.SetFirstParty(*b)
	}
	return ocu
}

// SetEnabled sets the "enabled" field.
func (ocu *OAuthClientUpdate) SetEnabled(b bool) *OAuthClientUpdate {
	ocu.mutation.SetEnabled(b)
	return ocu
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (ocu *OAuthClientUpdate) SetNillableEnabled(b *bool) *OAuthClientUpdate {
	if b != nil {
		ocu.SetEnabled(*b)
	}
	return ocu
}

// SetShowInNav sets the "show_in_nav" field.
func (ocu *OAuthClientUpdate) SetShowInNav(b bool) *OAuthClientUpdate {
	ocu.mutation.SetShowInNav(b)
	return ocu
}

// SetNillableShowInNav sets the "show_in_nav" field if the given value is not nil.
func (ocu *OAuthClientUpdate) SetNillableShowInNav(b *bool) *OAuthClientUpdate {
	if b != nil {
		ocu.SetShowInNav(*b)
	}
	return ocu
}

// SetLaunchURL sets the "launch_url" field.
func (ocu *OAuthClientUpdate) SetLaunchURL(s string) *OAuthClientUpdate {
	ocu.mutation.SetLaunchURL(s)
	return ocu
}

// SetNillableLaunchURL sets the "launch_url" field if the given value is not nil.
func (ocu *OAuthClientUpdate) SetNillableLaunchURL(s *string) *OAuthClientUpdate {
	if s != nil {
		ocu.SetLaunchURL(*s)
	}
	return ocu
}

// SetIcon sets the "icon" field.
func (ocu *OAuthClientUpdate) SetIcon(s string) *OAuthClientUpdate {
	ocu.mutation.SetIcon(s)
	return ocu
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (ocu *OAuthClientUpdate) SetNillableIcon(s *string) *OAuthClientUpdate {
	if s != nil {
		ocu.SetIcon(*s)
	}
	return ocu
}

// SetSortOrder sets the "sort_order" field.
func (ocu *OAuthClientUpdate) SetSortOrder(i int) *OAuthClientUpdate {
	ocu.mutation.ResetSortOrder()
	ocu.mutation.SetSortOrder(i)
	return ocu
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (ocu *OAuthClientUpdate) SetNillableSortOrder(i *int) *OAuthClientUpdate {
	if i != nil {
		ocu.SetSortOrder(*i)
	}
	return ocu
}

// AddSortOrder adds i to the "sort_order" field.
func (ocu *OAuthClientUpdate) AddSortOrder(i int) *OAuthClientUpdate {
	ocu.mutation.AddSortOrder(i)
	return ocu
}

// SetUpdatedAt sets the "updated_at" field.
func (ocu *OAuthClientUpdate) SetUpdatedAt(t time.Time) *OAuthClientUpdate {
	ocu.mutation.SetUpdatedAt(t)
	return ocu
}

// Mutation returns the OAuthClientMutation object of the builder.
func (ocu *OAuthClientUpdate) Mutation() *OAuthClientMutation {
	return ocu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ocu *OAuthClientUpdate) Save(ctx context.Context) (int, error) {
	ocu.defaults()
	return withHooks(ctx, ocu.sqlSave, ocu.mutation, ocu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ocu *OAuthClientUpdate) SaveX(ctx context.Context) int {
	affected, err := ocu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ocu *OAuthClientUpdate) Exec(ctx context.Context) error {
	_, err := ocu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocu *OAuthClientUpdate) ExecX(ctx context.Context) {
	if err := ocu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ocu *OAuthClientUpdate) defaults() {
	if _, ok := ocu.mutation.UpdatedAt(); !ok {
		v := oauthclient.UpdateDefaultUpdatedAt()
		ocu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ocu *OAuthClientUpdate) check() error {
	if v, ok := ocu.mutation.SecretHash(); ok {
		if err := oauthclient.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.secret_hash": %w`, err)}
		}
	}
	if v, ok := ocu.mutation.Name(); ok {
		if err := oauthclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ocu *OAuthClientUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OAuthClientUpdate {
	ocu.modifiers = append(ocu.modifiers, modifiers...)
	return ocu
}

func (ocu *OAuthClientUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ocu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthclient.Table, oauthclient.Columns, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt))
	if ps := ocu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ocu.mutation.SecretHash(); ok {
		_spec.SetField(oauthclient.FieldSecretHash, field.TypeString, value)
	}
	if value, ok := ocu.mutation.SecretHint(); ok {
		_spec.SetField(oauthclient.FieldSecretHint, field.TypeString, value)
	}
	if value, ok := ocu.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
	}
	if value, ok := ocu.mutation.Description(); ok {
		_spec.SetField(oauthclient.FieldDescription, field.TypeString, value)
	}
	if value, ok := ocu.mutation.RedirectUris(); ok {
		_spec.SetField(oauthclient.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := ocu.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldRedirectUris, value)
		})
	}
	if value, ok := ocu.mutation.AllowedScopes(); ok {
		_spec.SetField(oauthclient.FieldAllowedScopes, field.TypeJSON, value)
	}
	if value, ok := ocu.mutation.AppendedAllowedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldAllowedScopes, value)
		})
	}
	if value, ok := ocu.mutation.FirstParty(); ok {
		_spec.SetField(oauthclient.FieldFirstParty, field.TypeBool, value)
	}
	if value, ok := ocu.mutation.Enabled(); ok {
		_spec.SetField(oauthclient.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := ocu.mutation.ShowInNav(); ok {
		_spec.SetField(oauthclient.FieldShowInNav, field.TypeBool, value)
	}
	if value, ok := ocu.mutation.LaunchURL(); ok {
		_spec.SetField(oauthclient.FieldLaunchURL, field.TypeString, value)
	}
	if value, ok := ocu.mutation.Icon(); ok {
		_spec.SetField(oauthclient.FieldIcon, field.TypeString, value)
	}
	if value, ok := ocu.mutation.SortOrder(); ok {
		_spec.SetField(oauthclient.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := ocu.mutation.AddedSortOrder(); ok {
		_spec.AddField(oauthclient.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := ocu.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(ocu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ocu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ocu.mutation.done = true
	return n, nil
}

// OAuthClientUpdateOne is the builder for updating a single OAuthClient entity.
type OAuthClientUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OAuthClientMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetSecretHash sets the "secret_hash" field.
func (ocuo *OAuthClientUpdateOne) SetSecretHash(s string) *OAuthClientUpdateOne {
	ocuo.mutation.SetSecretHash(s)
	return ocuo
}

// SetNillableSecretHash sets the "secret_hash" field if the given value is not nil.
func (ocuo *OAuthClientUpdateOne) SetNillableSecretHash(s *string) *OAuthClientUpdateOne {
	if s != nil {
		ocuo.SetSecretHash(*s)
	}
	return ocuo
}

// SetSecretHint sets the "secret_hint" field.
func (ocuo *OAuthClientUpdateOne) SetSecretHint(s string) *OAuthClientUpdateOne {
	ocuo.mutation.SetSecretHint(s)
	return ocuo
}

// SetNillableSecretHint sets the "secret_hint" field if the given value is not nil.
func (ocuo *OAuthClientUpdateOne) SetNillableSecretHint(s *string) *OAuthClientUpdateOne {
	if s != nil {
		ocuo.SetSecretHint(*s)
	}
	return ocuo
}

// SetName sets the "name" field.
func (ocuo *OAuthClientUpdateOne) SetName(s string) *OAuthClientUpdateOne {
	ocuo.mutation.SetName(s)
	return ocuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ocuo *OAuthClientUpdateOne) SetNillableName(s *string) *OAuthClientUpdateOne {
	if s != nil {
		ocuo.SetName(*s)
	}
	return ocuo
}

// SetDescription sets the "description" field.
func (ocuo *OAuthClientUpdateOne) SetDescription(s string) *OAuthClientUpdateOne {
	ocuo.mutation.SetDescription(s)
	return ocuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ocuo *OAuthClientUpdateOne) SetNillableDescription(s *string) *OAuthClientUpdateOne {
	if s != nil {
		ocuo.SetDescription(*s)
	}
	return ocuo
}

// SetRedirectUris sets the "redirect_uris" field.
func (ocuo *OAuthClientUpdateOne) SetRedirectUris(s []string) *OAuthClientUpdateOne {
	ocuo.mutation.SetRedirectUris(s)
	return ocuo
}

// AppendRedirectUris appends s to the "redirect_uris" field.
func (ocuo *OAuthClientUpdateOne) AppendRedirectUris(s []string) *OAuthClientUpdateOne {
	ocuo.mutation.AppendRedirectUris(s)
	return ocuo
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (ocuo *OAuthClientUpdateOne) SetAllowedScopes(s []string) *OAuthClientUpdateOne {
	ocuo.mutation.SetAllowedScopes(s)
	return ocuo
}

// AppendAllowedScopes appends s to the "allowed_scopes" field.
func (ocuo *OAuthClientUpdateOne) AppendAllowedScopes(s []string) *OAuthClientUpdateOne {
	ocuo.mutation.AppendAllowedScopes(s)
	return ocuo
}

// SetFirstParty sets the "first_party" field.
func (ocuo *OAuthClientUpdateOne) SetFirstParty(b bool) *OAuthClientUpdateOne {
	ocuo.mutation.SetFirstParty(b)
	return ocuo
}

// SetNillableFirstParty sets the "first_party" field if the given value is not nil.
func (ocuo *OAuthClientUpdateOne) SetNillableFirstParty(b *bool) *OAuthClientUpdateOne {
	if b != nil {
		ocuo.SetFirstParty(*b)
	}
	return ocuo
}

// SetEnabled sets the "enabled" field.
func (ocuo *OAuthClientUpdateOne) SetEnabled(b bool) *OAuthClientUpdateOne {
	ocuo.mutation.SetEnabled(b)
	return ocuo
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (ocuo *OAuthClientUpdateOne) SetNillableEnabled(b *bool) *OAuthClientUpdateOne {
	if b != nil {
		ocuo.SetEnabled(*b)
	}
	return ocuo
}

// SetShowInNav sets the "show_in_nav" field.
func (ocuo *OAuthClientUpdateOne) SetShowInNav(b bool) *OAuthClientUpdateOne {
	ocuo.mutation.SetShowInNav(b)
	return ocuo
}

// SetNillableShowInNav sets the "show_in_nav" field if the given value is not nil.
func (ocuo *OAuthClientUpdateOne) SetNillableShowInNav(b *bool) *OAuthClientUpdateOne {
	if b != nil {
		ocuo.SetShowInNav(*b)
	}
	return ocuo
}

// SetLaunchURL sets the "launch_url" field.
func (ocuo *OAuthClientUpdateOne) SetLaunchURL(s string) *OAuthClientUpdateOne {
	ocuo.mutation.SetLaunchURL(s)
	return ocuo
}

// SetNillableLaunchURL sets the "launch_url" field if the given value is not nil.
func (ocuo *OAuthClientUpdateOne) SetNillableLaunchURL(s *string) *OAuthClientUpdateOne {
	if s != nil {
		ocuo.SetLaunchURL(*s)
	}
	return ocuo
}

// SetIcon sets the "icon" field.
func (ocuo *OAuthClientUpdateOne) SetIcon(s string) *OAuthClientUpdateOne {
	ocuo.mutation.SetIcon(s)
	return ocuo
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (ocuo *OAuthClientUpdateOne) SetNillableIcon(s *string) *OAuthClientUpdateOne {
	if s != nil {
		ocuo.SetIcon(*s)
	}
	return ocuo
}

// SetSortOrder sets the "sort_order" field.
func (ocuo *OAuthClientUpdateOne) SetSortOrder(i int) *OAuthClientUpdateOne {
	ocuo.mutation.ResetSortOrder()
	ocuo.mutation.SetSortOrder(i)
	return ocuo
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (ocuo *OAuthClientUpdateOne) SetNillableSortOrder(i *int) *OAuthClientUpdateOne {
	if i != nil {
		ocuo.SetSortOrder(*i)
	}
	return ocuo
}

// AddSortOrder adds i to the "sort_order" field.
func (ocuo *OAuthClientUpdateOne) AddSortOrder(i int) *OAuthClientUpdateOne {
	ocuo.mutation.AddSortOrder(i)
	return ocuo
}

// SetUpdatedAt sets the "updated_at" field.
func (ocuo *OAuthClientUpdateOne) SetUpdatedAt(t time.Time) *OAuthClientUpdateOne {
	ocuo.mutation.SetUpdatedAt(t)
	return ocuo
}

// Mutation returns the OAuthClientMutation object of the builder.
func (ocuo *OAuthClientUpdateOne) Mutation() *OAuthClientMutation {
	return ocuo.mutation
}

// Where appends a list predicates to the OAuthClientUpdate builder.
func (ocuo *OAuthClientUpdateOne) Where(ps ...predicate.OAuthClient) *OAuthClientUpdateOne {
	ocuo.mutation.Where(ps...)
	return ocuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ocuo *OAuthClientUpdateOne) Select(field string, fields ...string) *OAuthClientUpdateOne {
	ocuo.fields = append([]string{field}, fields...)
	return ocuo
}

// Save executes the query and returns the updated OAuthClient entity.
func (ocuo *OAuthClientUpdateOne) Save(ctx context.Context) (*OAuthClient, error) {
	ocuo.defaults()
	return withHooks(ctx, ocuo.sqlSave, ocuo.mutation, ocuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ocuo *OAuthClientUpdateOne) SaveX(ctx context.Context) *OAuthClient {
	node, err := ocuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ocuo *OAuthClientUpdateOne) Exec(ctx context.Context) error {
	_, err := ocuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocuo *OAuthClientUpdateOne) ExecX(ctx context.Context) {
	if err := ocuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ocuo *OAuthClientUpdateOne) defaults() {
	if _, ok := ocuo.mutation.UpdatedAt(); !ok {
		v := oauthclient.UpdateDefaultUpdatedAt()
		ocuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ocuo *OAuthClientUpdateOne) check() error {
	if v, ok := ocuo.mutation.SecretHash(); ok {
		if err := oauthclient.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.secret_hash": %w`, err)}
		}
	}
	if v, ok := ocuo.mutation.Name(); ok {
		if err := oauthclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ocuo *OAuthClientUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OAuthClientUpdateOne {
	ocuo.modifiers = append(ocuo.modifiers, modifiers...)
	return ocuo
}

func (ocuo *OAuthClientUpdateOne) sqlSave(ctx context.Context) (_node *OAuthClient, err error) {
	if err := ocuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthclient.Table, oauthclient.Columns, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt))
	id, ok := ocuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthClient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ocuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthclient.FieldID)
		for _, f := range fields {
			if !oauthclient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ocuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ocuo.mutation.SecretHash(); ok {
		_spec.SetField(oauthclient.FieldSecretHash, field.TypeString, value)
	}
	if value, ok := ocuo.mutation.SecretHint(); ok {
		_spec.SetField(oauthclient.FieldSecretHint, field.TypeString, value)
	}
	if value, ok := ocuo.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
	}
	if value, ok := ocuo.mutation.Description(); ok {
		_spec.SetField(oauthclient.FieldDescription, field.TypeString, value)
	}
	if value, ok := ocuo.mutation.RedirectUris(); ok {
		_spec.SetField(oauthclient.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := ocuo.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldRedirectUris, value)
		})
	}
	if value, ok := ocuo.mutation.AllowedScopes(); ok {
		_spec.SetField(oauthclient.FieldAllowedScopes, field.TypeJSON, value)
	}
	if value, ok := ocuo.mutation.AppendedAllowedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldAllowedScopes, value)
		})
	}
	if value, ok := ocuo.mutation.FirstParty(); ok {
		_spec.SetField(oauthclient.FieldFirstParty, field.TypeBool, value)
	}
	if value, ok := ocuo.mutation.Enabled(); ok {
		_spec.SetField(oauthclient.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := ocuo.mutation.ShowInNav(); ok {
		_spec.SetField(oauthclient.FieldShowInNav, field.TypeBool, value)
	}
	if value, ok := ocuo.mutation.LaunchURL(); ok {
		_spec.SetField(oauthclient.FieldLaunchURL, field.TypeString, value)
	}
	if value, ok := ocuo.mutation.Icon(); ok {
		_spec.SetField(oauthclient.FieldIcon, field.TypeString, value)
	}
	if value, ok := ocuo.mutation.SortOrder(); ok {
		_spec.SetField(oauthclient.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := ocuo.mutation.AddedSortOrder(); ok {
		_spec.AddField(oauthclient.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := ocuo.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(ocuo.modifiers...)
	_node = &OAuthClient{config: ocuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ocuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ocuo.mutation.done = true
	return _node, nil
}
