// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/paymentorder"
)

// PaymentOrderCreate is the builder for creating a PaymentOrder entity.
type PaymentOrderCreate struct {
	config
	mutation *PaymentOrderMutation
	hooks    []Hook
}

// SetOutTradeNo sets the "out_trade_no" field.
func (poc *PaymentOrderCreate) SetOutTradeNo(s string) *PaymentOrderCreate {
	poc.mutation.SetOutTradeNo(s)
	return poc
}

// SetUserID sets the "user_id" field.
func (poc *PaymentOrderCreate) SetUserID(i int) *PaymentOrderCreate {
	poc.mutation.SetUserID(i)
	return poc
}

// SetMethod sets the "method" field.
func (poc *PaymentOrderCreate) SetMethod(s string) *PaymentOrderCreate {
	poc.mutation.SetMethod(s)
	return poc
}

// SetProviderID sets the "provider_id" field.
func (poc *PaymentOrderCreate) SetProviderID(s string) *PaymentOrderCreate {
	poc.mutation.SetProviderID(s)
	return poc
}

// SetAmount sets the "amount" field.
func (poc *PaymentOrderCreate) SetAmount(f float64) *PaymentOrderCreate {
	poc.mutation.SetAmount(f)
	return poc
}

// SetStatus sets the "status" field.
func (poc *PaymentOrderCreate) SetStatus(s string) *PaymentOrderCreate {
	poc.mutation.SetStatus(s)
	return poc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableStatus(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetStatus(*s)
	}
	return poc
}

// SetSubject sets the "subject" field.
func (poc *PaymentOrderCreate) SetSubject(s string) *PaymentOrderCreate {
	poc.mutation.SetSubject(s)
	return poc
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableSubject(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetSubject(*s)
	}
	return poc
}

// SetClientIP sets the "client_ip" field.
func (poc *PaymentOrderCreate) SetClientIP(s string) *PaymentOrderCreate {
	poc.mutation.SetClientIP(s)
	return poc
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableClientIP(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetClientIP(*s)
	}
	return poc
}

// SetPaymentURL sets the "payment_url" field.
func (poc *PaymentOrderCreate) SetPaymentURL(s string) *PaymentOrderCreate {
	poc.mutation.SetPaymentURL(s)
	return poc
}

// SetNillablePaymentURL sets the "payment_url" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillablePaymentURL(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetPaymentURL(*s)
	}
	return poc
}

// SetQrCodeContent sets the "qr_code_content" field.
func (poc *PaymentOrderCreate) SetQrCodeContent(s string) *PaymentOrderCreate {
	poc.mutation.SetQrCodeContent(s)
	return poc
}

// SetNillableQrCodeContent sets the "qr_code_content" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableQrCodeContent(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetQrCodeContent(*s)
	}
	return poc
}

// SetNotifyPayload sets the "notify_payload" field.
func (poc *PaymentOrderCreate) SetNotifyPayload(s string) *PaymentOrderCreate {
	poc.mutation.SetNotifyPayload(s)
	return poc
}

// SetNillableNotifyPayload sets the "notify_payload" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableNotifyPayload(s *string) *PaymentOrderCreate {
	if s != nil {
		poc.SetNotifyPayload(*s)
	}
	return poc
}

// SetPaidAt sets the "paid_at" field.
func (poc *PaymentOrderCreate) SetPaidAt(t time.Time) *PaymentOrderCreate {
	poc.mutation.SetPaidAt(t)
	return poc
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillablePaidAt(t *time.Time) *PaymentOrderCreate {
	if t != nil {
		poc.SetPaidAt(*t)
	}
	return poc
}

// SetExpiresAt sets the "expires_at" field.
func (poc *PaymentOrderCreate) SetExpiresAt(t time.Time) *PaymentOrderCreate {
	poc.mutation.SetExpiresAt(t)
	return poc
}

// SetCreatedAt sets the "created_at" field.
func (poc *PaymentOrderCreate) SetCreatedAt(t time.Time) *PaymentOrderCreate {
	poc.mutation.SetCreatedAt(t)
	return poc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableCreatedAt(t *time.Time) *PaymentOrderCreate {
	if t != nil {
		poc.SetCreatedAt(*t)
	}
	return poc
}

// SetUpdatedAt sets the "updated_at" field.
func (poc *PaymentOrderCreate) SetUpdatedAt(t time.Time) *PaymentOrderCreate {
	poc.mutation.SetUpdatedAt(t)
	return poc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (poc *PaymentOrderCreate) SetNillableUpdatedAt(t *time.Time) *PaymentOrderCreate {
	if t != nil {
		poc.SetUpdatedAt(*t)
	}
	return poc
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (poc *PaymentOrderCreate) Mutation() *PaymentOrderMutation {
	return poc.mutation
}

// Save creates the PaymentOrder in the database.
func (poc *PaymentOrderCreate) Save(ctx context.Context) (*PaymentOrder, error) {
	poc.defaults()
	return withHooks(ctx, poc.sqlSave, poc.mutation, poc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (poc *PaymentOrderCreate) SaveX(ctx context.Context) *PaymentOrder {
	v, err := poc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (poc *PaymentOrderCreate) Exec(ctx context.Context) error {
	_, err := poc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (poc *PaymentOrderCreate) ExecX(ctx context.Context) {
	if err := poc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (poc *PaymentOrderCreate) defaults() {
	if _, ok := poc.mutation.Status(); !ok {
		v := paymentorder.DefaultStatus
		poc.mutation.SetStatus(v)
	}
	if _, ok := poc.mutation.Subject(); !ok {
		v := paymentorder.DefaultSubject
		poc.mutation.SetSubject(v)
	}
	if _, ok := poc.mutation.ClientIP(); !ok {
		v := paymentorder.DefaultClientIP
		poc.mutation.SetClientIP(v)
	}
	if _, ok := poc.mutation.PaymentURL(); !ok {
		v := paymentorder.DefaultPaymentURL
		poc.mutation.SetPaymentURL(v)
	}
	if _, ok := poc.mutation.QrCodeContent(); !ok {
		v := paymentorder.DefaultQrCodeContent
		poc.mutation.SetQrCodeContent(v)
	}
	if _, ok := poc.mutation.NotifyPayload(); !ok {
		v := paymentorder.DefaultNotifyPayload
		poc.mutation.SetNotifyPayload(v)
	}
	if _, ok := poc.mutation.CreatedAt(); !ok {
		v := paymentorder.DefaultCreatedAt()
		poc.mutation.SetCreatedAt(v)
	}
	if _, ok := poc.mutation.UpdatedAt(); !ok {
		v := paymentorder.DefaultUpdatedAt()
		poc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (poc *PaymentOrderCreate) check() error {
	if _, ok := poc.mutation.OutTradeNo(); !ok {
		return &ValidationError{Name: "out_trade_no", err: errors.New(`ent: missing required field "PaymentOrder.out_trade_no"`)}
	}
	if v, ok := poc.mutation.OutTradeNo(); ok {
		if err := paymentorder.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.out_trade_no": %w`, err)}
		}
	}
	if _, ok := poc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PaymentOrder.user_id"`)}
	}
	if _, ok := poc.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "PaymentOrder.method"`)}
	}
	if v, ok := poc.mutation.Method(); ok {
		if err := paymentorder.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.method": %w`, err)}
		}
	}
	if _, ok := poc.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "PaymentOrder.provider_id"`)}
	}
	if v, ok := poc.mutation.ProviderID(); ok {
		if err := paymentorder.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_id": %w`, err)}
		}
	}
	if _, ok := poc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "PaymentOrder.amount"`)}
	}
	if _, ok := poc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentOrder.status"`)}
	}
	if _, ok := poc.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "PaymentOrder.subject"`)}
	}
	if _, ok := poc.mutation.ClientIP(); !ok {
		return &ValidationError{Name: "client_ip", err: errors.New(`ent: missing required field "PaymentOrder.client_ip"`)}
	}
	if _, ok := poc.mutation.PaymentURL(); !ok {
		return &ValidationError{Name: "payment_url", err: errors.New(`ent: missing required field "PaymentOrder.payment_url"`)}
	}
	if _, ok := poc.mutation.QrCodeContent(); !ok {
		return &ValidationError{Name: "qr_code_content", err: errors.New(`ent: missing required field "PaymentOrder.qr_code_content"`)}
	}
	if _, ok := poc.mutation.NotifyPayload(); !ok {
		return &ValidationError{Name: "notify_payload", err: errors.New(`ent: missing required field "PaymentOrder.notify_payload"`)}
	}
	if _, ok := poc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "PaymentOrder.expires_at"`)}
	}
	if _, ok := poc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentOrder.created_at"`)}
	}
	if _, ok := poc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentOrder.updated_at"`)}
	}
	return nil
}

func (poc *PaymentOrderCreate) sqlSave(ctx context.Context) (*PaymentOrder, error) {
	if err := poc.check(); err != nil {
		return nil, err
	}
	_node, _spec := poc.createSpec()
	if err := sqlgraph.CreateNode(ctx, poc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	poc.mutation.id = &_node.ID
	poc.mutation.done = true
	return _node, nil
}

func (poc *PaymentOrderCreate) createSpec() (*PaymentOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentOrder{config: poc.config}
		_spec = sqlgraph.NewCreateSpec(paymentorder.Table, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt))
	)
	if value, ok := poc.mutation.OutTradeNo(); ok {
		_spec.SetField(paymentorder.FieldOutTradeNo, field.TypeString, value)
		_node.OutTradeNo = value
	}
	if value, ok := poc.mutation.UserID(); ok {
		_spec.SetField(paymentorder.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := poc.mutation.Method(); ok {
		_spec.SetField(paymentorder.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := poc.mutation.ProviderID(); ok {
		_spec.SetField(paymentorder.FieldProviderID, field.TypeString, value)
		_node.ProviderID = value
	}
	if value, ok := poc.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := poc.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := poc.mutation.Subject(); ok {
		_spec.SetField(paymentorder.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := poc.mutation.ClientIP(); ok {
		_spec.SetField(paymentorder.FieldClientIP, field.TypeString, value)
		_node.ClientIP = value
	}
	if value, ok := poc.mutation.PaymentURL(); ok {
		_spec.SetField(paymentorder.FieldPaymentURL, field.TypeString, value)
		_node.PaymentURL = value
	}
	if value, ok := poc.mutation.QrCodeContent(); ok {
		_spec.SetField(paymentorder.FieldQrCodeContent, field.TypeString, value)
		_node.QrCodeContent = value
	}
	if value, ok := poc.mutation.NotifyPayload(); ok {
		_spec.SetField(paymentorder.FieldNotifyPayload, field.TypeString, value)
		_node.NotifyPayload = value
	}
	if value, ok := poc.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := poc.mutation.ExpiresAt(); ok {
		_spec.SetField(paymentorder.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := poc.mutation.CreatedAt(); ok {
		_spec.SetField(paymentorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := poc.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PaymentOrderCreateBulk is the builder for creating many PaymentOrder entities in bulk.
type PaymentOrderCreateBulk struct {
	config
	err      error
	builders []*PaymentOrderCreate
}

// Save creates the PaymentOrder entities in the database.
func (pocb *PaymentOrderCreateBulk) Save(ctx context.Context) ([]*PaymentOrder, error) {
	if pocb.err != nil {
		return nil, pocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pocb.builders))
	nodes := make([]*PaymentOrder, len(pocb.builders))
	mutators := make([]Mutator, len(pocb.builders))
	for i := range pocb.builders {
		func(i int, root context.Context) {
			builder := pocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pocb *PaymentOrderCreateBulk) SaveX(ctx context.Context) []*PaymentOrder {
	v, err := pocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pocb *PaymentOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := pocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pocb *PaymentOrderCreateBulk) ExecX(ctx context.Context) {
	if err := pocb.Exec(ctx); err != nil {
		panic(err)
	}
}
