// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/pluginsource"
)

// PluginSource is the model entity for the PluginSource schema.
type PluginSource struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// IsOfficial holds the value of the "is_official" field.
	IsOfficial bool `json:"is_official,omitempty"`
	// LastSyncAt holds the value of the "last_sync_at" field.
	LastSyncAt *time.Time `json:"last_sync_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PluginSource) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pluginsource.FieldIsOfficial:
			values[i] = new(sql.NullBool)
		case pluginsource.FieldID:
			values[i] = new(sql.NullInt64)
		case pluginsource.FieldName, pluginsource.FieldURL:
			values[i] = new(sql.NullString)
		case pluginsource.FieldLastSyncAt, pluginsource.FieldCreatedAt, pluginsource.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PluginSource fields.
func (ps *PluginSource) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pluginsource.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ps.ID = int(value.Int64)
		case pluginsource.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ps.Name = value.String
			}
		case pluginsource.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				ps.URL = value.String
			}
		case pluginsource.FieldIsOfficial:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_official", values[i])
			} else if value.Valid {
				ps.IsOfficial = value.Bool
			}
		case pluginsource.FieldLastSyncAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_at", values[i])
			} else if value.Valid {
				ps.LastSyncAt = new(time.Time)
				*ps.LastSyncAt = value.Time
			}
		case pluginsource.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ps.CreatedAt = value.Time
			}
		case pluginsource.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ps.UpdatedAt = value.Time
			}
		default:
			ps.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PluginSource.
// This includes values selected through modifiers, order, etc.
func (ps *PluginSource) Value(name string) (ent.Value, error) {
	return ps.selectValues.Get(name)
}

// Update returns a builder for updating this PluginSource.
// Note that you need to call PluginSource.Unwrap() before calling this method if this PluginSource
// was returned from a transaction, and the transaction was committed or rolled back.
func (ps *PluginSource) Update() *PluginSourceUpdateOne {
	return NewPluginSourceClient(ps.config).UpdateOne(ps)
}

// Unwrap unwraps the PluginSource entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ps *PluginSource) Unwrap() *PluginSource {
	_tx, ok := ps.config.driver.(*txDriver)
	if !ok {
		panic("ent: PluginSource is not a transactional entity")
	}
	ps.config.driver = _tx.drv
	return ps
}

// String implements the fmt.Stringer.
func (ps *PluginSource) String() string {
	var builder strings.Builder
	builder.WriteString("PluginSource(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ps.ID))
	builder.WriteString("name=")
	builder.WriteString(ps.Name)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(ps.URL)
	builder.WriteString(", ")
	builder.WriteString("is_official=")
	builder.WriteString(fmt.Sprintf("%v", ps.IsOfficial))
	builder.WriteString(", ")
	if v := ps.LastSyncAt; v != nil {
		builder.WriteString("last_sync_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ps.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ps.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PluginSources is a parsable slice of PluginSource.
type PluginSources []*PluginSource
