// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/pluginsource"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// PluginSourceUpdate is the builder for updating PluginSource entities.
type PluginSourceUpdate struct {
	config
	hooks    []Hook
	mutation *PluginSourceMutation
}

// Where appends a list predicates to the PluginSourceUpdate builder.
func (psu *PluginSourceUpdate) Where(ps ...predicate.PluginSource) *PluginSourceUpdate {
	psu.mutation.Where(ps...)
	return psu
}

// SetName sets the "name" field.
func (psu *PluginSourceUpdate) SetName(s string) *PluginSourceUpdate {
	psu.mutation.SetName(s)
	return psu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (psu *PluginSourceUpdate) SetNillableName(s *string) *PluginSourceUpdate {
	if s != nil {
		psu.SetName(*s)
	}
	return psu
}

// SetURL sets the "url" field.
func (psu *PluginSourceUpdate) SetURL(s string) *PluginSourceUpdate {
	psu.mutation.SetURL(s)
	return psu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (psu *PluginSourceUpdate) SetNillableURL(s *string) *PluginSourceUpdate {
	if s != nil {
		psu.SetURL(*s)
	}
	return psu
}

// SetIsOfficial sets the "is_official" field.
func (psu *PluginSourceUpdate) SetIsOfficial(b bool) *PluginSourceUpdate {
	psu.mutation.SetIsOfficial(b)
	return psu
}

// SetNillableIsOfficial sets the "is_official" field if the given value is not nil.
func (psu *PluginSourceUpdate) SetNillableIsOfficial(b *bool) *PluginSourceUpdate {
	if b != nil {
		psu.SetIsOfficial(*b)
	}
	return psu
}

// SetLastSyncAt sets the "last_sync_at" field.
func (psu *PluginSourceUpdate) SetLastSyncAt(t time.Time) *PluginSourceUpdate {
	psu.mutation.SetLastSyncAt(t)
	return psu
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (psu *PluginSourceUpdate) SetNillableLastSyncAt(t *time.Time) *PluginSourceUpdate {
	if t != nil {
		psu.SetLastSyncAt(*t)
	}
	return psu
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (psu *PluginSourceUpdate) ClearLastSyncAt() *PluginSourceUpdate {
	psu.mutation.ClearLastSyncAt()
	return psu
}

// SetUpdatedAt sets the "updated_at" field.
func (psu *PluginSourceUpdate) SetUpdatedAt(t time.Time) *PluginSourceUpdate {
	psu.mutation.SetUpdatedAt(t)
	return psu
}

// Mutation returns the PluginSourceMutation object of the builder.
func (psu *PluginSourceUpdate) Mutation() *PluginSourceMutation {
	return psu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (psu *PluginSourceUpdate) Save(ctx context.Context) (int, error) {
	psu.defaults()
	return withHooks(ctx, psu.sqlSave, psu.mutation, psu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psu *PluginSourceUpdate) SaveX(ctx context.Context) int {
	affected, err := psu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (psu *PluginSourceUpdate) Exec(ctx context.Context) error {
	_, err := psu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psu *PluginSourceUpdate) ExecX(ctx context.Context) {
	if err := psu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (psu *PluginSourceUpdate) defaults() {
	if _, ok := psu.mutation.UpdatedAt(); !ok {
		v := pluginsource.UpdateDefaultUpdatedAt()
		psu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (psu *PluginSourceUpdate) check() error {
	if v, ok := psu.mutation.Name(); ok {
		if err := pluginsource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PluginSource.name": %w`, err)}
		}
	}
	if v, ok := psu.mutation.URL(); ok {
		if err := pluginsource.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "PluginSource.url": %w`, err)}
		}
	}
	return nil
}

func (psu *PluginSourceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := psu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginsource.Table, pluginsource.Columns, sqlgraph.NewFieldSpec(pluginsource.FieldID, field.TypeInt))
	if ps := psu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := psu.mutation.Name(); ok {
		_spec.SetField(pluginsource.FieldName, field.TypeString, value)
	}
	if value, ok := psu.mutation.URL(); ok {
		_spec.SetField(pluginsource.FieldURL, field.TypeString, value)
	}
	if value, ok := psu.mutation.IsOfficial(); ok {
		_spec.SetField(pluginsource.FieldIsOfficial, field.TypeBool, value)
	}
	if value, ok := psu.mutation.LastSyncAt(); ok {
		_spec.SetField(pluginsource.FieldLastSyncAt, field.TypeTime, value)
	}
	if psu.mutation.LastSyncAtCleared() {
		_spec.ClearField(pluginsource.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := psu.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginsource.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, psu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	psu.mutation.done = true
	return n, nil
}

// PluginSourceUpdateOne is the builder for updating a single PluginSource entity.
type PluginSourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginSourceMutation
}

// SetName sets the "name" field.
func (psuo *PluginSourceUpdateOne) SetName(s string) *PluginSourceUpdateOne {
	psuo.mutation.SetName(s)
	return psuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (psuo *PluginSourceUpdateOne) SetNillableName(s *string) *PluginSourceUpdateOne {
	if s != nil {
		psuo.SetName(*s)
	}
	return psuo
}

// SetURL sets the "url" field.
func (psuo *PluginSourceUpdateOne) SetURL(s string) *PluginSourceUpdateOne {
	psuo.mutation.SetURL(s)
	return psuo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (psuo *PluginSourceUpdateOne) SetNillableURL(s *string) *PluginSourceUpdateOne {
	if s != nil {
		psuo.SetURL(*s)
	}
	return psuo
}

// SetIsOfficial sets the "is_official" field.
func (psuo *PluginSourceUpdateOne) SetIsOfficial(b bool) *PluginSourceUpdateOne {
	psuo.mutation.SetIsOfficial(b)
	return psuo
}

// SetNillableIsOfficial sets the "is_official" field if the given value is not nil.
func (psuo *PluginSourceUpdateOne) SetNillableIsOfficial(b *bool) *PluginSourceUpdateOne {
	if b != nil {
		psuo.SetIsOfficial(*b)
	}
	return psuo
}

// SetLastSyncAt sets the "last_sync_at" field.
func (psuo *PluginSourceUpdateOne) SetLastSyncAt(t time.Time) *PluginSourceUpdateOne {
	psuo.mutation.SetLastSyncAt(t)
	return psuo
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (psuo *PluginSourceUpdateOne) SetNillableLastSyncAt(t *time.Time) *PluginSourceUpdateOne {
	if t != nil {
		psuo.SetLastSyncAt(*t)
	}
	return psuo
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (psuo *PluginSourceUpdateOne) ClearLastSyncAt() *PluginSourceUpdateOne {
	psuo.mutation.ClearLastSyncAt()
	return psuo
}

// SetUpdatedAt sets the "updated_at" field.
func (psuo *PluginSourceUpdateOne) SetUpdatedAt(t time.Time) *PluginSourceUpdateOne {
	psuo.mutation.SetUpdatedAt(t)
	return psuo
}

// Mutation returns the PluginSourceMutation object of the builder.
func (psuo *PluginSourceUpdateOne) Mutation() *PluginSourceMutation {
	return psuo.mutation
}

// Where appends a list predicates to the PluginSourceUpdate builder.
func (psuo *PluginSourceUpdateOne) Where(ps ...predicate.PluginSource) *PluginSourceUpdateOne {
	psuo.mutation.Where(ps...)
	return psuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (psuo *PluginSourceUpdateOne) Select(field string, fields ...string) *PluginSourceUpdateOne {
	psuo.fields = append([]string{field}, fields...)
	return psuo
}

// Save executes the query and returns the updated PluginSource entity.
func (psuo *PluginSourceUpdateOne) Save(ctx context.Context) (*PluginSource, error) {
	psuo.defaults()
	return withHooks(ctx, psuo.sqlSave, psuo.mutation, psuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psuo *PluginSourceUpdateOne) SaveX(ctx context.Context) *PluginSource {
	node, err := psuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (psuo *PluginSourceUpdateOne) Exec(ctx context.Context) error {
	_, err := psuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psuo *PluginSourceUpdateOne) ExecX(ctx context.Context) {
	if err := psuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (psuo *PluginSourceUpdateOne) defaults() {
	if _, ok := psuo.mutation.UpdatedAt(); !ok {
		v := pluginsource.UpdateDefaultUpdatedAt()
		psuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (psuo *PluginSourceUpdateOne) check() error {
	if v, ok := psuo.mutation.Name(); ok {
		if err := pluginsource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PluginSource.name": %w`, err)}
		}
	}
	if v, ok := psuo.mutation.URL(); ok {
		if err := pluginsource.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "PluginSource.url": %w`, err)}
		}
	}
	return nil
}

func (psuo *PluginSourceUpdateOne) sqlSave(ctx context.Context) (_node *PluginSource, err error) {
	if err := psuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginsource.Table, pluginsource.Columns, sqlgraph.NewFieldSpec(pluginsource.FieldID, field.TypeInt))
	id, ok := psuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PluginSource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := psuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pluginsource.FieldID)
		for _, f := range fields {
			if !pluginsource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pluginsource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := psuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := psuo.mutation.Name(); ok {
		_spec.SetField(pluginsource.FieldName, field.TypeString, value)
	}
	if value, ok := psuo.mutation.URL(); ok {
		_spec.SetField(pluginsource.FieldURL, field.TypeString, value)
	}
	if value, ok := psuo.mutation.IsOfficial(); ok {
		_spec.SetField(pluginsource.FieldIsOfficial, field.TypeBool, value)
	}
	if value, ok := psuo.mutation.LastSyncAt(); ok {
		_spec.SetField(pluginsource.FieldLastSyncAt, field.TypeTime, value)
	}
	if psuo.mutation.LastSyncAtCleared() {
		_spec.ClearField(pluginsource.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := psuo.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginsource.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PluginSource{config: psuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, psuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	psuo.mutation.done = true
	return _node, nil
}
