// Code generated by ent, DO NOT EDIT.

package channelkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldName, v))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldAPIKey, v))
}

// ErrorMsg applies equality check predicate on the "error_msg" field. It's identical to ErrorMsgEQ.
func ErrorMsg(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldErrorMsg, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldPriority, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldWeight, v))
}

// MaxConcurrency applies equality check predicate on the "max_concurrency" field. It's identical to MaxConcurrencyEQ.
func MaxConcurrency(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldMaxConcurrency, v))
}

// MaxRpm applies equality check predicate on the "max_rpm" field. It's identical to MaxRpmEQ.
func MaxRpm(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldMaxRpm, v))
}

// CostRatio applies equality check predicate on the "cost_ratio" field. It's identical to CostRatioEQ.
func CostRatio(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldCostRatio, v))
}

// TestModel applies equality check predicate on the "test_model" field. It's identical to TestModelEQ.
func TestModel(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldTestModel, v))
}

// ResponseTimeMs applies equality check predicate on the "response_time_ms" field. It's identical to ResponseTimeMsEQ.
func ResponseTimeMs(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldResponseTimeMs, v))
}

// TestedAt applies equality check predicate on the "tested_at" field. It's identical to TestedAtEQ.
func TestedAt(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldTestedAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldBalance, v))
}

// BalanceUpdatedAt applies equality check predicate on the "balance_updated_at" field. It's identical to BalanceUpdatedAtEQ.
func BalanceUpdatedAt(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldBalanceUpdatedAt, v))
}

// BalanceCheckEnabled applies equality check predicate on the "balance_check_enabled" field. It's identical to BalanceCheckEnabledEQ.
func BalanceCheckEnabled(v bool) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldBalanceCheckEnabled, v))
}

// ProbeEnabled applies equality check predicate on the "probe_enabled" field. It's identical to ProbeEnabledEQ.
func ProbeEnabled(v bool) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldProbeEnabled, v))
}

// ProbeModel applies equality check predicate on the "probe_model" field. It's identical to ProbeModelEQ.
func ProbeModel(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldProbeModel, v))
}

// ConsecutiveFailures applies equality check predicate on the "consecutive_failures" field. It's identical to ConsecutiveFailuresEQ.
func ConsecutiveFailures(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveSuccesses applies equality check predicate on the "consecutive_successes" field. It's identical to ConsecutiveSuccessesEQ.
func ConsecutiveSuccesses(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldConsecutiveSuccesses, v))
}

// LastProbeAt applies equality check predicate on the "last_probe_at" field. It's identical to LastProbeAtEQ.
func LastProbeAt(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldLastProbeAt, v))
}

// UpstreamRateEnabled applies equality check predicate on the "upstream_rate_enabled" field. It's identical to UpstreamRateEnabledEQ.
func UpstreamRateEnabled(v bool) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldUpstreamRateEnabled, v))
}

// UpstreamRatePath applies equality check predicate on the "upstream_rate_path" field. It's identical to UpstreamRatePathEQ.
func UpstreamRatePath(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldUpstreamRatePath, v))
}

// UpstreamRate applies equality check predicate on the "upstream_rate" field. It's identical to UpstreamRateEQ.
func UpstreamRate(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldUpstreamRate, v))
}

// UpstreamRateAt applies equality check predicate on the "upstream_rate_at" field. It's identical to UpstreamRateAtEQ.
func UpstreamRateAt(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldUpstreamRateAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldType, vs...))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "api_key" field.
func APIKeyContains(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "api_key" field.
func APIKeyHasPrefix(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "api_key" field.
func APIKeyHasSuffix(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyEqualFold applies the EqualFold predicate on the "api_key" field.
func APIKeyEqualFold(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "api_key" field.
func APIKeyContainsFold(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldContainsFold(FieldAPIKey, v))
}

// ModelMappingIsNil applies the IsNil predicate on the "model_mapping" field.
func ModelMappingIsNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIsNull(FieldModelMapping))
}

// ModelMappingNotNil applies the NotNil predicate on the "model_mapping" field.
func ModelMappingNotNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotNull(FieldModelMapping))
}

// ParamOverrideIsNil applies the IsNil predicate on the "param_override" field.
func ParamOverrideIsNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIsNull(FieldParamOverride))
}

// ParamOverrideNotNil applies the NotNil predicate on the "param_override" field.
func ParamOverrideNotNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotNull(FieldParamOverride))
}

// HeaderOverrideIsNil applies the IsNil predicate on the "header_override" field.
func HeaderOverrideIsNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIsNull(FieldHeaderOverride))
}

// HeaderOverrideNotNil applies the NotNil predicate on the "header_override" field.
func HeaderOverrideNotNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotNull(FieldHeaderOverride))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldStatus, vs...))
}

// ErrorMsgEQ applies the EQ predicate on the "error_msg" field.
func ErrorMsgEQ(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldErrorMsg, v))
}

// ErrorMsgNEQ applies the NEQ predicate on the "error_msg" field.
func ErrorMsgNEQ(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldErrorMsg, v))
}

// ErrorMsgIn applies the In predicate on the "error_msg" field.
func ErrorMsgIn(vs ...string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldErrorMsg, vs...))
}

// ErrorMsgNotIn applies the NotIn predicate on the "error_msg" field.
func ErrorMsgNotIn(vs ...string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldErrorMsg, vs...))
}

// ErrorMsgGT applies the GT predicate on the "error_msg" field.
func ErrorMsgGT(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldErrorMsg, v))
}

// ErrorMsgGTE applies the GTE predicate on the "error_msg" field.
func ErrorMsgGTE(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldErrorMsg, v))
}

// ErrorMsgLT applies the LT predicate on the "error_msg" field.
func ErrorMsgLT(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldErrorMsg, v))
}

// ErrorMsgLTE applies the LTE predicate on the "error_msg" field.
func ErrorMsgLTE(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldErrorMsg, v))
}

// ErrorMsgContains applies the Contains predicate on the "error_msg" field.
func ErrorMsgContains(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldContains(FieldErrorMsg, v))
}

// ErrorMsgHasPrefix applies the HasPrefix predicate on the "error_msg" field.
func ErrorMsgHasPrefix(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldHasPrefix(FieldErrorMsg, v))
}

// ErrorMsgHasSuffix applies the HasSuffix predicate on the "error_msg" field.
func ErrorMsgHasSuffix(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldHasSuffix(FieldErrorMsg, v))
}

// ErrorMsgEqualFold applies the EqualFold predicate on the "error_msg" field.
func ErrorMsgEqualFold(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEqualFold(FieldErrorMsg, v))
}

// ErrorMsgContainsFold applies the ContainsFold predicate on the "error_msg" field.
func ErrorMsgContainsFold(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldContainsFold(FieldErrorMsg, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldPriority, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldWeight, v))
}

// MaxConcurrencyEQ applies the EQ predicate on the "max_concurrency" field.
func MaxConcurrencyEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyNEQ applies the NEQ predicate on the "max_concurrency" field.
func MaxConcurrencyNEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyIn applies the In predicate on the "max_concurrency" field.
func MaxConcurrencyIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyNotIn applies the NotIn predicate on the "max_concurrency" field.
func MaxConcurrencyNotIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyGT applies the GT predicate on the "max_concurrency" field.
func MaxConcurrencyGT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldMaxConcurrency, v))
}

// MaxConcurrencyGTE applies the GTE predicate on the "max_concurrency" field.
func MaxConcurrencyGTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldMaxConcurrency, v))
}

// MaxConcurrencyLT applies the LT predicate on the "max_concurrency" field.
func MaxConcurrencyLT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldMaxConcurrency, v))
}

// MaxConcurrencyLTE applies the LTE predicate on the "max_concurrency" field.
func MaxConcurrencyLTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldMaxConcurrency, v))
}

// MaxRpmEQ applies the EQ predicate on the "max_rpm" field.
func MaxRpmEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldMaxRpm, v))
}

// MaxRpmNEQ applies the NEQ predicate on the "max_rpm" field.
func MaxRpmNEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldMaxRpm, v))
}

// MaxRpmIn applies the In predicate on the "max_rpm" field.
func MaxRpmIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldMaxRpm, vs...))
}

// MaxRpmNotIn applies the NotIn predicate on the "max_rpm" field.
func MaxRpmNotIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldMaxRpm, vs...))
}

// MaxRpmGT applies the GT predicate on the "max_rpm" field.
func MaxRpmGT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldMaxRpm, v))
}

// MaxRpmGTE applies the GTE predicate on the "max_rpm" field.
func MaxRpmGTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldMaxRpm, v))
}

// MaxRpmLT applies the LT predicate on the "max_rpm" field.
func MaxRpmLT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldMaxRpm, v))
}

// MaxRpmLTE applies the LTE predicate on the "max_rpm" field.
func MaxRpmLTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldMaxRpm, v))
}

// CostRatioEQ applies the EQ predicate on the "cost_ratio" field.
func CostRatioEQ(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldCostRatio, v))
}

// CostRatioNEQ applies the NEQ predicate on the "cost_ratio" field.
func CostRatioNEQ(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldCostRatio, v))
}

// CostRatioIn applies the In predicate on the "cost_ratio" field.
func CostRatioIn(vs ...float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldCostRatio, vs...))
}

// CostRatioNotIn applies the NotIn predicate on the "cost_ratio" field.
func CostRatioNotIn(vs ...float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldCostRatio, vs...))
}

// CostRatioGT applies the GT predicate on the "cost_ratio" field.
func CostRatioGT(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldCostRatio, v))
}

// CostRatioGTE applies the GTE predicate on the "cost_ratio" field.
func CostRatioGTE(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldCostRatio, v))
}

// CostRatioLT applies the LT predicate on the "cost_ratio" field.
func CostRatioLT(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldCostRatio, v))
}

// CostRatioLTE applies the LTE predicate on the "cost_ratio" field.
func CostRatioLTE(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldCostRatio, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotNull(FieldTags))
}

// TestModelEQ applies the EQ predicate on the "test_model" field.
func TestModelEQ(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldTestModel, v))
}

// TestModelNEQ applies the NEQ predicate on the "test_model" field.
func TestModelNEQ(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldTestModel, v))
}

// TestModelIn applies the In predicate on the "test_model" field.
func TestModelIn(vs ...string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldTestModel, vs...))
}

// TestModelNotIn applies the NotIn predicate on the "test_model" field.
func TestModelNotIn(vs ...string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldTestModel, vs...))
}

// TestModelGT applies the GT predicate on the "test_model" field.
func TestModelGT(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldTestModel, v))
}

// TestModelGTE applies the GTE predicate on the "test_model" field.
func TestModelGTE(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldTestModel, v))
}

// TestModelLT applies the LT predicate on the "test_model" field.
func TestModelLT(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldTestModel, v))
}

// TestModelLTE applies the LTE predicate on the "test_model" field.
func TestModelLTE(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldTestModel, v))
}

// TestModelContains applies the Contains predicate on the "test_model" field.
func TestModelContains(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldContains(FieldTestModel, v))
}

// TestModelHasPrefix applies the HasPrefix predicate on the "test_model" field.
func TestModelHasPrefix(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldHasPrefix(FieldTestModel, v))
}

// TestModelHasSuffix applies the HasSuffix predicate on the "test_model" field.
func TestModelHasSuffix(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldHasSuffix(FieldTestModel, v))
}

// TestModelEqualFold applies the EqualFold predicate on the "test_model" field.
func TestModelEqualFold(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEqualFold(FieldTestModel, v))
}

// TestModelContainsFold applies the ContainsFold predicate on the "test_model" field.
func TestModelContainsFold(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldContainsFold(FieldTestModel, v))
}

// ResponseTimeMsEQ applies the EQ predicate on the "response_time_ms" field.
func ResponseTimeMsEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldResponseTimeMs, v))
}

// ResponseTimeMsNEQ applies the NEQ predicate on the "response_time_ms" field.
func ResponseTimeMsNEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldResponseTimeMs, v))
}

// ResponseTimeMsIn applies the In predicate on the "response_time_ms" field.
func ResponseTimeMsIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldResponseTimeMs, vs...))
}

// ResponseTimeMsNotIn applies the NotIn predicate on the "response_time_ms" field.
func ResponseTimeMsNotIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldResponseTimeMs, vs...))
}

// ResponseTimeMsGT applies the GT predicate on the "response_time_ms" field.
func ResponseTimeMsGT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldResponseTimeMs, v))
}

// ResponseTimeMsGTE applies the GTE predicate on the "response_time_ms" field.
func ResponseTimeMsGTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldResponseTimeMs, v))
}

// ResponseTimeMsLT applies the LT predicate on the "response_time_ms" field.
func ResponseTimeMsLT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldResponseTimeMs, v))
}

// ResponseTimeMsLTE applies the LTE predicate on the "response_time_ms" field.
func ResponseTimeMsLTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldResponseTimeMs, v))
}

// TestedAtEQ applies the EQ predicate on the "tested_at" field.
func TestedAtEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldTestedAt, v))
}

// TestedAtNEQ applies the NEQ predicate on the "tested_at" field.
func TestedAtNEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldTestedAt, v))
}

// TestedAtIn applies the In predicate on the "tested_at" field.
func TestedAtIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldTestedAt, vs...))
}

// TestedAtNotIn applies the NotIn predicate on the "tested_at" field.
func TestedAtNotIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldTestedAt, vs...))
}

// TestedAtGT applies the GT predicate on the "tested_at" field.
func TestedAtGT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldTestedAt, v))
}

// TestedAtGTE applies the GTE predicate on the "tested_at" field.
func TestedAtGTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldTestedAt, v))
}

// TestedAtLT applies the LT predicate on the "tested_at" field.
func TestedAtLT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldTestedAt, v))
}

// TestedAtLTE applies the LTE predicate on the "tested_at" field.
func TestedAtLTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldTestedAt, v))
}

// TestedAtIsNil applies the IsNil predicate on the "tested_at" field.
func TestedAtIsNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIsNull(FieldTestedAt))
}

// TestedAtNotNil applies the NotNil predicate on the "tested_at" field.
func TestedAtNotNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotNull(FieldTestedAt))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotNull(FieldLastUsedAt))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldBalance, v))
}

// BalanceUpdatedAtEQ applies the EQ predicate on the "balance_updated_at" field.
func BalanceUpdatedAtEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldBalanceUpdatedAt, v))
}

// BalanceUpdatedAtNEQ applies the NEQ predicate on the "balance_updated_at" field.
func BalanceUpdatedAtNEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldBalanceUpdatedAt, v))
}

// BalanceUpdatedAtIn applies the In predicate on the "balance_updated_at" field.
func BalanceUpdatedAtIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldBalanceUpdatedAt, vs...))
}

// BalanceUpdatedAtNotIn applies the NotIn predicate on the "balance_updated_at" field.
func BalanceUpdatedAtNotIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldBalanceUpdatedAt, vs...))
}

// BalanceUpdatedAtGT applies the GT predicate on the "balance_updated_at" field.
func BalanceUpdatedAtGT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldBalanceUpdatedAt, v))
}

// BalanceUpdatedAtGTE applies the GTE predicate on the "balance_updated_at" field.
func BalanceUpdatedAtGTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldBalanceUpdatedAt, v))
}

// BalanceUpdatedAtLT applies the LT predicate on the "balance_updated_at" field.
func BalanceUpdatedAtLT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldBalanceUpdatedAt, v))
}

// BalanceUpdatedAtLTE applies the LTE predicate on the "balance_updated_at" field.
func BalanceUpdatedAtLTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldBalanceUpdatedAt, v))
}

// BalanceUpdatedAtIsNil applies the IsNil predicate on the "balance_updated_at" field.
func BalanceUpdatedAtIsNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIsNull(FieldBalanceUpdatedAt))
}

// BalanceUpdatedAtNotNil applies the NotNil predicate on the "balance_updated_at" field.
func BalanceUpdatedAtNotNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotNull(FieldBalanceUpdatedAt))
}

// BalanceCheckEnabledEQ applies the EQ predicate on the "balance_check_enabled" field.
func BalanceCheckEnabledEQ(v bool) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldBalanceCheckEnabled, v))
}

// BalanceCheckEnabledNEQ applies the NEQ predicate on the "balance_check_enabled" field.
func BalanceCheckEnabledNEQ(v bool) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldBalanceCheckEnabled, v))
}

// ProbeEnabledEQ applies the EQ predicate on the "probe_enabled" field.
func ProbeEnabledEQ(v bool) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldProbeEnabled, v))
}

// ProbeEnabledNEQ applies the NEQ predicate on the "probe_enabled" field.
func ProbeEnabledNEQ(v bool) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldProbeEnabled, v))
}

// ProbeModelEQ applies the EQ predicate on the "probe_model" field.
func ProbeModelEQ(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldProbeModel, v))
}

// ProbeModelNEQ applies the NEQ predicate on the "probe_model" field.
func ProbeModelNEQ(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldProbeModel, v))
}

// ProbeModelIn applies the In predicate on the "probe_model" field.
func ProbeModelIn(vs ...string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldProbeModel, vs...))
}

// ProbeModelNotIn applies the NotIn predicate on the "probe_model" field.
func ProbeModelNotIn(vs ...string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldProbeModel, vs...))
}

// ProbeModelGT applies the GT predicate on the "probe_model" field.
func ProbeModelGT(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldProbeModel, v))
}

// ProbeModelGTE applies the GTE predicate on the "probe_model" field.
func ProbeModelGTE(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldProbeModel, v))
}

// ProbeModelLT applies the LT predicate on the "probe_model" field.
func ProbeModelLT(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldProbeModel, v))
}

// ProbeModelLTE applies the LTE predicate on the "probe_model" field.
func ProbeModelLTE(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldProbeModel, v))
}

// ProbeModelContains applies the Contains predicate on the "probe_model" field.
func ProbeModelContains(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldContains(FieldProbeModel, v))
}

// ProbeModelHasPrefix applies the HasPrefix predicate on the "probe_model" field.
func ProbeModelHasPrefix(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldHasPrefix(FieldProbeModel, v))
}

// ProbeModelHasSuffix applies the HasSuffix predicate on the "probe_model" field.
func ProbeModelHasSuffix(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldHasSuffix(FieldProbeModel, v))
}

// ProbeModelEqualFold applies the EqualFold predicate on the "probe_model" field.
func ProbeModelEqualFold(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEqualFold(FieldProbeModel, v))
}

// ProbeModelContainsFold applies the ContainsFold predicate on the "probe_model" field.
func ProbeModelContainsFold(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldContainsFold(FieldProbeModel, v))
}

// HealthStatusEQ applies the EQ predicate on the "health_status" field.
func HealthStatusEQ(v HealthStatus) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldHealthStatus, v))
}

// HealthStatusNEQ applies the NEQ predicate on the "health_status" field.
func HealthStatusNEQ(v HealthStatus) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldHealthStatus, v))
}

// HealthStatusIn applies the In predicate on the "health_status" field.
func HealthStatusIn(vs ...HealthStatus) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldHealthStatus, vs...))
}

// HealthStatusNotIn applies the NotIn predicate on the "health_status" field.
func HealthStatusNotIn(vs ...HealthStatus) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldHealthStatus, vs...))
}

// ConsecutiveFailuresEQ applies the EQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresNEQ applies the NEQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresIn applies the In predicate on the "consecutive_failures" field.
func ConsecutiveFailuresIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresNotIn applies the NotIn predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNotIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresGT applies the GT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresGTE applies the GTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLT applies the LT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLTE applies the LTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldConsecutiveFailures, v))
}

// ConsecutiveSuccessesEQ applies the EQ predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldConsecutiveSuccesses, v))
}

// ConsecutiveSuccessesNEQ applies the NEQ predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesNEQ(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldConsecutiveSuccesses, v))
}

// ConsecutiveSuccessesIn applies the In predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldConsecutiveSuccesses, vs...))
}

// ConsecutiveSuccessesNotIn applies the NotIn predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesNotIn(vs ...int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldConsecutiveSuccesses, vs...))
}

// ConsecutiveSuccessesGT applies the GT predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesGT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldConsecutiveSuccesses, v))
}

// ConsecutiveSuccessesGTE applies the GTE predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesGTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldConsecutiveSuccesses, v))
}

// ConsecutiveSuccessesLT applies the LT predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesLT(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldConsecutiveSuccesses, v))
}

// ConsecutiveSuccessesLTE applies the LTE predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesLTE(v int) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldConsecutiveSuccesses, v))
}

// LastProbeAtEQ applies the EQ predicate on the "last_probe_at" field.
func LastProbeAtEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldLastProbeAt, v))
}

// LastProbeAtNEQ applies the NEQ predicate on the "last_probe_at" field.
func LastProbeAtNEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldLastProbeAt, v))
}

// LastProbeAtIn applies the In predicate on the "last_probe_at" field.
func LastProbeAtIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldLastProbeAt, vs...))
}

// LastProbeAtNotIn applies the NotIn predicate on the "last_probe_at" field.
func LastProbeAtNotIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldLastProbeAt, vs...))
}

// LastProbeAtGT applies the GT predicate on the "last_probe_at" field.
func LastProbeAtGT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldLastProbeAt, v))
}

// LastProbeAtGTE applies the GTE predicate on the "last_probe_at" field.
func LastProbeAtGTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldLastProbeAt, v))
}

// LastProbeAtLT applies the LT predicate on the "last_probe_at" field.
func LastProbeAtLT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldLastProbeAt, v))
}

// LastProbeAtLTE applies the LTE predicate on the "last_probe_at" field.
func LastProbeAtLTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldLastProbeAt, v))
}

// LastProbeAtIsNil applies the IsNil predicate on the "last_probe_at" field.
func LastProbeAtIsNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIsNull(FieldLastProbeAt))
}

// LastProbeAtNotNil applies the NotNil predicate on the "last_probe_at" field.
func LastProbeAtNotNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotNull(FieldLastProbeAt))
}

// UpstreamRateEnabledEQ applies the EQ predicate on the "upstream_rate_enabled" field.
func UpstreamRateEnabledEQ(v bool) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldUpstreamRateEnabled, v))
}

// UpstreamRateEnabledNEQ applies the NEQ predicate on the "upstream_rate_enabled" field.
func UpstreamRateEnabledNEQ(v bool) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldUpstreamRateEnabled, v))
}

// UpstreamRatePathEQ applies the EQ predicate on the "upstream_rate_path" field.
func UpstreamRatePathEQ(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldUpstreamRatePath, v))
}

// UpstreamRatePathNEQ applies the NEQ predicate on the "upstream_rate_path" field.
func UpstreamRatePathNEQ(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldUpstreamRatePath, v))
}

// UpstreamRatePathIn applies the In predicate on the "upstream_rate_path" field.
func UpstreamRatePathIn(vs ...string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldUpstreamRatePath, vs...))
}

// UpstreamRatePathNotIn applies the NotIn predicate on the "upstream_rate_path" field.
func UpstreamRatePathNotIn(vs ...string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldUpstreamRatePath, vs...))
}

// UpstreamRatePathGT applies the GT predicate on the "upstream_rate_path" field.
func UpstreamRatePathGT(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldUpstreamRatePath, v))
}

// UpstreamRatePathGTE applies the GTE predicate on the "upstream_rate_path" field.
func UpstreamRatePathGTE(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldUpstreamRatePath, v))
}

// UpstreamRatePathLT applies the LT predicate on the "upstream_rate_path" field.
func UpstreamRatePathLT(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldUpstreamRatePath, v))
}

// UpstreamRatePathLTE applies the LTE predicate on the "upstream_rate_path" field.
func UpstreamRatePathLTE(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldUpstreamRatePath, v))
}

// UpstreamRatePathContains applies the Contains predicate on the "upstream_rate_path" field.
func UpstreamRatePathContains(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldContains(FieldUpstreamRatePath, v))
}

// UpstreamRatePathHasPrefix applies the HasPrefix predicate on the "upstream_rate_path" field.
func UpstreamRatePathHasPrefix(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldHasPrefix(FieldUpstreamRatePath, v))
}

// UpstreamRatePathHasSuffix applies the HasSuffix predicate on the "upstream_rate_path" field.
func UpstreamRatePathHasSuffix(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldHasSuffix(FieldUpstreamRatePath, v))
}

// UpstreamRatePathEqualFold applies the EqualFold predicate on the "upstream_rate_path" field.
func UpstreamRatePathEqualFold(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEqualFold(FieldUpstreamRatePath, v))
}

// UpstreamRatePathContainsFold applies the ContainsFold predicate on the "upstream_rate_path" field.
func UpstreamRatePathContainsFold(v string) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldContainsFold(FieldUpstreamRatePath, v))
}

// UpstreamRateEQ applies the EQ predicate on the "upstream_rate" field.
func UpstreamRateEQ(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldUpstreamRate, v))
}

// UpstreamRateNEQ applies the NEQ predicate on the "upstream_rate" field.
func UpstreamRateNEQ(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldUpstreamRate, v))
}

// UpstreamRateIn applies the In predicate on the "upstream_rate" field.
func UpstreamRateIn(vs ...float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldUpstreamRate, vs...))
}

// UpstreamRateNotIn applies the NotIn predicate on the "upstream_rate" field.
func UpstreamRateNotIn(vs ...float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldUpstreamRate, vs...))
}

// UpstreamRateGT applies the GT predicate on the "upstream_rate" field.
func UpstreamRateGT(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldUpstreamRate, v))
}

// UpstreamRateGTE applies the GTE predicate on the "upstream_rate" field.
func UpstreamRateGTE(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldUpstreamRate, v))
}

// UpstreamRateLT applies the LT predicate on the "upstream_rate" field.
func UpstreamRateLT(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldUpstreamRate, v))
}

// UpstreamRateLTE applies the LTE predicate on the "upstream_rate" field.
func UpstreamRateLTE(v float64) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldUpstreamRate, v))
}

// UpstreamRateAtEQ applies the EQ predicate on the "upstream_rate_at" field.
func UpstreamRateAtEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldUpstreamRateAt, v))
}

// UpstreamRateAtNEQ applies the NEQ predicate on the "upstream_rate_at" field.
func UpstreamRateAtNEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldUpstreamRateAt, v))
}

// UpstreamRateAtIn applies the In predicate on the "upstream_rate_at" field.
func UpstreamRateAtIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldUpstreamRateAt, vs...))
}

// UpstreamRateAtNotIn applies the NotIn predicate on the "upstream_rate_at" field.
func UpstreamRateAtNotIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldUpstreamRateAt, vs...))
}

// UpstreamRateAtGT applies the GT predicate on the "upstream_rate_at" field.
func UpstreamRateAtGT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldUpstreamRateAt, v))
}

// UpstreamRateAtGTE applies the GTE predicate on the "upstream_rate_at" field.
func UpstreamRateAtGTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldUpstreamRateAt, v))
}

// UpstreamRateAtLT applies the LT predicate on the "upstream_rate_at" field.
func UpstreamRateAtLT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldUpstreamRateAt, v))
}

// UpstreamRateAtLTE applies the LTE predicate on the "upstream_rate_at" field.
func UpstreamRateAtLTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldUpstreamRateAt, v))
}

// UpstreamRateAtIsNil applies the IsNil predicate on the "upstream_rate_at" field.
func UpstreamRateAtIsNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIsNull(FieldUpstreamRateAt))
}

// UpstreamRateAtNotNil applies the NotNil predicate on the "upstream_rate_at" field.
func UpstreamRateAtNotNil() predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotNull(FieldUpstreamRateAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ChannelKey {
	return predicate.ChannelKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.ChannelKey {
	return predicate.ChannelKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.ChannelKey {
	return predicate.ChannelKey(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.ChannelKey {
	return predicate.ChannelKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, GroupsTable, GroupsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.Group) predicate.ChannelKey {
	return predicate.ChannelKey(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.ChannelKey {
	return predicate.ChannelKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.ChannelKey {
	return predicate.ChannelKey(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChannelKey) predicate.ChannelKey {
	return predicate.ChannelKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChannelKey) predicate.ChannelKey {
	return predicate.ChannelKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChannelKey) predicate.ChannelKey {
	return predicate.ChannelKey(sql.NotPredicates(p))
}
