// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "key_hint", Type: field.TypeString, Default: ""},
		{Name: "key_hash", Type: field.TypeString},
		{Name: "key_encrypted", Type: field.TypeString, Nullable: true},
		{Name: "ip_whitelist", Type: field.TypeJSON, Nullable: true},
		{Name: "ip_blacklist", Type: field.TypeJSON, Nullable: true},
		{Name: "quota_usd", Type: field.TypeFloat64, Default: 0},
		{Name: "used_quota", Type: field.TypeFloat64, Default: 0},
		{Name: "used_quota_actual", Type: field.TypeFloat64, Default: 0},
		{Name: "sell_rate", Type: field.TypeFloat64, Default: 0},
		{Name: "max_concurrency", Type: field.TypeInt, Default: 0},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "provisioned_by", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "group_api_keys", Type: field.TypeInt, Nullable: true},
		{Name: "user_api_keys", Type: field.TypeInt},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_groups_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[17]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[18]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apikey_key_hash",
				Unique:  true,
				Columns: []*schema.Column{APIKeysColumns[3]},
			},
			{
				Name:    "apikey_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[13], APIKeysColumns[15]},
			},
			{
				Name:    "apikey_provisioned_by_user_api_keys",
				Unique:  true,
				Columns: []*schema.Column{APIKeysColumns[14], APIKeysColumns[18]},
				Annotation: &entsql.IndexAnnotation{
					Where: "provisioned_by <> ''",
				},
			},
		},
	}
	// AnnouncementsColumns holds the columns for the "announcements" table.
	AnnouncementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "status", Type: field.TypeString, Default: "draft"},
		{Name: "notify_mode", Type: field.TypeString, Default: "silent"},
		{Name: "starts_at", Type: field.TypeTime, Nullable: true},
		{Name: "ends_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AnnouncementsTable holds the schema information for the "announcements" table.
	AnnouncementsTable = &schema.Table{
		Name:       "announcements",
		Columns:    AnnouncementsColumns,
		PrimaryKey: []*schema.Column{AnnouncementsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "announcement_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementsColumns[3], AnnouncementsColumns[7]},
			},
		},
	}
	// AnnouncementReadsColumns holds the columns for the "announcement_reads" table.
	AnnouncementReadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "announcement_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "read_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AnnouncementReadsTable holds the schema information for the "announcement_reads" table.
	AnnouncementReadsTable = &schema.Table{
		Name:       "announcement_reads",
		Columns:    AnnouncementReadsColumns,
		PrimaryKey: []*schema.Column{AnnouncementReadsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "announcementread_announcement_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{AnnouncementReadsColumns[1], AnnouncementReadsColumns[2]},
			},
			{
				Name:    "announcementread_user_id",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementReadsColumns[2]},
			},
		},
	}
	// BalanceLogsColumns holds the columns for the "balance_logs" table.
	BalanceLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"add", "subtract", "set"}},
		{Name: "amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "before_balance", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "after_balance", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "remark", Type: field.TypeString, Default: ""},
		{Name: "user_id_snapshot", Type: field.TypeInt, Default: 0},
		{Name: "user_email_snapshot", Type: field.TypeString, Default: ""},
		{Name: "idempotency_key", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_balance_logs", Type: field.TypeInt, Nullable: true},
	}
	// BalanceLogsTable holds the schema information for the "balance_logs" table.
	BalanceLogsTable = &schema.Table{
		Name:       "balance_logs",
		Columns:    BalanceLogsColumns,
		PrimaryKey: []*schema.Column{BalanceLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "balance_logs_users_balance_logs",
				Columns:    []*schema.Column{BalanceLogsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "balancelog_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{BalanceLogsColumns[8]},
			},
			{
				Name:    "balancelog_user_id_snapshot_created_at",
				Unique:  false,
				Columns: []*schema.Column{BalanceLogsColumns[6], BalanceLogsColumns[9]},
			},
		},
	}
	// ChannelsColumns holds the columns for the "channels" table.
	ChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"openai_compatible", "anthropic", "gemini", "custom"}},
		{Name: "base_url", Type: field.TypeString},
		{Name: "api_keys", Type: field.TypeJSON},
		{Name: "models", Type: field.TypeJSON},
		{Name: "model_mapping", Type: field.TypeJSON, Nullable: true},
		{Name: "param_override", Type: field.TypeJSON, Nullable: true},
		{Name: "header_override", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled_manual", "disabled_auto"}, Default: "enabled"},
		{Name: "error_msg", Type: field.TypeString, Default: ""},
		{Name: "priority", Type: field.TypeInt, Default: 50},
		{Name: "weight", Type: field.TypeInt, Default: 10},
		{Name: "max_concurrency", Type: field.TypeInt, Default: 0},
		{Name: "max_rpm", Type: field.TypeInt, Default: 0},
		{Name: "cost_ratio", Type: field.TypeFloat64, Default: 1},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "test_model", Type: field.TypeString, Default: ""},
		{Name: "response_time_ms", Type: field.TypeInt, Default: 0},
		{Name: "tested_at", Type: field.TypeTime, Nullable: true},
		{Name: "balance", Type: field.TypeFloat64, Default: 0},
		{Name: "balance_updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ChannelsTable holds the schema information for the "channels" table.
	ChannelsTable = &schema.Table{
		Name:       "channels",
		Columns:    ChannelsColumns,
		PrimaryKey: []*schema.Column{ChannelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "channel_type_status",
				Unique:  false,
				Columns: []*schema.Column{ChannelsColumns[2], ChannelsColumns[9]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "platform", Type: field.TypeString, Default: ""},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1},
		{Name: "is_exclusive", Type: field.TypeBool, Default: false},
		{Name: "status_visible", Type: field.TypeBool, Default: true},
		{Name: "note", Type: field.TypeString, Default: ""},
		{Name: "sort_weight", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
	}
	// ModelPricesColumns holds the columns for the "model_prices" table.
	ModelPricesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "model", Type: field.TypeString, Unique: true},
		{Name: "input_price", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "output_price", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "cached_input_price", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "cache_creation_price", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "cache_creation_1h_price", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "per_request_price", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "pricing_extra", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tag_id", Type: field.TypeInt, Nullable: true},
	}
	// ModelPricesTable holds the schema information for the "model_prices" table.
	ModelPricesTable = &schema.Table{
		Name:       "model_prices",
		Columns:    ModelPricesColumns,
		PrimaryKey: []*schema.Column{ModelPricesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "model_prices_model_tags_prices",
				Columns:    []*schema.Column{ModelPricesColumns[11]},
				RefColumns: []*schema.Column{ModelTagsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ModelTagsColumns holds the columns for the "model_tags" table.
	ModelTagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ModelTagsTable holds the schema information for the "model_tags" table.
	ModelTagsTable = &schema.Table{
		Name:       "model_tags",
		Columns:    ModelTagsColumns,
		PrimaryKey: []*schema.Column{ModelTagsColumns[0]},
	}
	// OauthClientsColumns holds the columns for the "oauth_clients" table.
	OauthClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "client_id", Type: field.TypeString, Unique: true},
		{Name: "secret_hash", Type: field.TypeString},
		{Name: "secret_hint", Type: field.TypeString, Default: ""},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "redirect_uris", Type: field.TypeJSON},
		{Name: "first_party", Type: field.TypeBool, Default: false},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "show_in_nav", Type: field.TypeBool, Default: false},
		{Name: "launch_url", Type: field.TypeString, Default: ""},
		{Name: "icon", Type: field.TypeString, Default: ""},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OauthClientsTable holds the schema information for the "oauth_clients" table.
	OauthClientsTable = &schema.Table{
		Name:       "oauth_clients",
		Columns:    OauthClientsColumns,
		PrimaryKey: []*schema.Column{OauthClientsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthclient_enabled_show_in_nav_sort_order",
				Unique:  false,
				Columns: []*schema.Column{OauthClientsColumns[8], OauthClientsColumns[9], OauthClientsColumns[12]},
			},
		},
	}
	// PaymentOrdersColumns holds the columns for the "payment_orders" table.
	PaymentOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "out_trade_no", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "method", Type: field.TypeString},
		{Name: "provider_id", Type: field.TypeString},
		{Name: "amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "subject", Type: field.TypeString, Default: ""},
		{Name: "client_ip", Type: field.TypeString, Default: ""},
		{Name: "payment_url", Type: field.TypeString, Default: ""},
		{Name: "qr_code_content", Type: field.TypeString, Default: ""},
		{Name: "notify_payload", Type: field.TypeString, Default: ""},
		{Name: "paid_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PaymentOrdersTable holds the schema information for the "payment_orders" table.
	PaymentOrdersTable = &schema.Table{
		Name:       "payment_orders",
		Columns:    PaymentOrdersColumns,
		PrimaryKey: []*schema.Column{PaymentOrdersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "payment_order_user_created_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[2], PaymentOrdersColumns[14]},
			},
			{
				Name:    "payment_order_status_expires_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[6], PaymentOrdersColumns[13]},
			},
			{
				Name:    "payment_order_created_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[14]},
			},
		},
	}
	// PaymentProviderConfigsColumns holds the columns for the "payment_provider_configs" table.
	PaymentProviderConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "provider_key", Type: field.TypeString, Unique: true},
		{Name: "kind", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "config", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PaymentProviderConfigsTable holds the schema information for the "payment_provider_configs" table.
	PaymentProviderConfigsTable = &schema.Table{
		Name:       "payment_provider_configs",
		Columns:    PaymentProviderConfigsColumns,
		PrimaryKey: []*schema.Column{PaymentProviderConfigsColumns[0]},
	}
	// RedemptionCodesColumns holds the columns for the "redemption_codes" table.
	RedemptionCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "value", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "status", Type: field.TypeString, Default: "unused"},
		{Name: "remark", Type: field.TypeString, Default: ""},
		{Name: "used_by_id", Type: field.TypeInt, Default: 0},
		{Name: "used_by_email", Type: field.TypeString, Default: ""},
		{Name: "used_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RedemptionCodesTable holds the schema information for the "redemption_codes" table.
	RedemptionCodesTable = &schema.Table{
		Name:       "redemption_codes",
		Columns:    RedemptionCodesColumns,
		PrimaryKey: []*schema.Column{RedemptionCodesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "redemption_code_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{RedemptionCodesColumns[3], RedemptionCodesColumns[9]},
			},
			{
				Name:    "redemption_code_used_by_used_at",
				Unique:  false,
				Columns: []*schema.Column{RedemptionCodesColumns[5], RedemptionCodesColumns[7]},
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Default: ""},
		{Name: "group", Type: field.TypeString, Default: "general"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// UpstreamRequestLogsColumns holds the columns for the "upstream_request_logs" table.
	UpstreamRequestLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "request_id", Type: field.TypeString},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"relay", "channel_test"}},
		{Name: "phase", Type: field.TypeString, Default: ""},
		{Name: "status_code", Type: field.TypeInt, Default: 0},
		{Name: "error_type", Type: field.TypeString, Default: ""},
		{Name: "error_code", Type: field.TypeString, Default: ""},
		{Name: "message", Type: field.TypeString, Default: ""},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "attempt_chain", Type: field.TypeJSON, Nullable: true},
		{Name: "billed", Type: field.TypeBool, Default: false},
		{Name: "model", Type: field.TypeString, Default: ""},
		{Name: "endpoint", Type: field.TypeString, Default: ""},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "user_id", Type: field.TypeInt, Default: 0},
		{Name: "user_email_snapshot", Type: field.TypeString, Default: ""},
		{Name: "api_key_id", Type: field.TypeInt, Default: 0},
		{Name: "group_id", Type: field.TypeInt, Default: 0},
		{Name: "channel_id", Type: field.TypeInt, Default: 0},
		{Name: "channel_name", Type: field.TypeString, Default: ""},
		{Name: "ip_address", Type: field.TypeString, Default: ""},
		{Name: "user_agent", Type: field.TypeString, Default: ""},
		{Name: "duration_ms", Type: field.TypeInt64, Default: 0},
		{Name: "repeat_count", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UpstreamRequestLogsTable holds the schema information for the "upstream_request_logs" table.
	UpstreamRequestLogsTable = &schema.Table{
		Name:       "upstream_request_logs",
		Columns:    UpstreamRequestLogsColumns,
		PrimaryKey: []*schema.Column{UpstreamRequestLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "upstream_req_log_created_at",
				Unique:  false,
				Columns: []*schema.Column{UpstreamRequestLogsColumns[24]},
			},
			{
				Name:    "upstream_req_log_user_created_at",
				Unique:  false,
				Columns: []*schema.Column{UpstreamRequestLogsColumns[14], UpstreamRequestLogsColumns[24]},
			},
			{
				Name:    "upstream_req_log_api_key_created_at",
				Unique:  false,
				Columns: []*schema.Column{UpstreamRequestLogsColumns[16], UpstreamRequestLogsColumns[24]},
			},
			{
				Name:    "upstream_req_log_channel_created_at",
				Unique:  false,
				Columns: []*schema.Column{UpstreamRequestLogsColumns[18], UpstreamRequestLogsColumns[24]},
			},
			{
				Name:    "upstream_req_log_phase_created_at",
				Unique:  false,
				Columns: []*schema.Column{UpstreamRequestLogsColumns[3], UpstreamRequestLogsColumns[24]},
			},
			{
				Name:    "upstream_req_log_request_id",
				Unique:  false,
				Columns: []*schema.Column{UpstreamRequestLogsColumns[1]},
			},
		},
	}
	// UsageLogsColumns holds the columns for the "usage_logs" table.
	UsageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "model", Type: field.TypeString},
		{Name: "input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "output_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cached_input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_creation_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_creation_5m_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_creation_1h_tokens", Type: field.TypeInt, Default: 0},
		{Name: "calls", Type: field.TypeInt, Default: 0},
		{Name: "input_price", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "output_price", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "cached_input_price", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "cache_creation_price", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "cache_creation_1h_price", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "input_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "output_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "cached_input_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "cache_creation_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "total_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "actual_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "billed_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1},
		{Name: "sell_rate", Type: field.TypeFloat64, Default: 0},
		{Name: "account_rate_multiplier", Type: field.TypeFloat64, Default: 1},
		{Name: "service_tier", Type: field.TypeString, Default: ""},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "duration_ms", Type: field.TypeInt64, Default: 0},
		{Name: "first_token_ms", Type: field.TypeInt64, Default: 0},
		{Name: "user_agent", Type: field.TypeString, Default: ""},
		{Name: "ip_address", Type: field.TypeString, Default: ""},
		{Name: "endpoint", Type: field.TypeString, Default: ""},
		{Name: "source", Type: field.TypeString, Default: "relay"},
		{Name: "request_id", Type: field.TypeString, Default: ""},
		{Name: "user_id_snapshot", Type: field.TypeInt, Default: 0},
		{Name: "user_email_snapshot", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "api_key_usage_logs", Type: field.TypeInt, Nullable: true},
		{Name: "channel_usage_logs", Type: field.TypeInt, Nullable: true},
		{Name: "group_usage_logs", Type: field.TypeInt, Nullable: true},
		{Name: "user_usage_logs", Type: field.TypeInt, Nullable: true},
	}
	// UsageLogsTable holds the schema information for the "usage_logs" table.
	UsageLogsTable = &schema.Table{
		Name:       "usage_logs",
		Columns:    UsageLogsColumns,
		PrimaryKey: []*schema.Column{UsageLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "usage_logs_api_keys_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[36]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_channels_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[37]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_groups_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[38]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_users_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[39]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usage_log_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[35]},
			},
			{
				Name:    "usage_log_user_snapshot_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[33], UsageLogsColumns[35]},
			},
			{
				Name:    "usage_log_model_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[1], UsageLogsColumns[35]},
			},
			{
				Name:    "usage_log_user",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[39]},
			},
			{
				Name:    "usage_log_api_key",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[36]},
			},
			{
				Name:    "usage_log_channel",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[37]},
			},
			{
				Name:    "usage_log_group",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[38]},
			},
			{
				Name:    "usage_log_api_key_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[36], UsageLogsColumns[35]},
			},
			{
				Name:    "usage_log_channel_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[37], UsageLogsColumns[35]},
			},
			{
				Name:    "usage_log_group_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[38], UsageLogsColumns[35]},
			},
			{
				Name:    "usage_log_request_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[32]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Default: ""},
		{Name: "balance", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "user"}, Default: "user"},
		{Name: "max_concurrency", Type: field.TypeInt, Default: 0},
		{Name: "group_rates", Type: field.TypeJSON, Nullable: true},
		{Name: "balance_alert_threshold", Type: field.TypeFloat64, Default: 0},
		{Name: "balance_alert_notified", Type: field.TypeBool, Default: false},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// ChannelGroupsColumns holds the columns for the "channel_groups" table.
	ChannelGroupsColumns = []*schema.Column{
		{Name: "channel_id", Type: field.TypeInt},
		{Name: "group_id", Type: field.TypeInt},
	}
	// ChannelGroupsTable holds the schema information for the "channel_groups" table.
	ChannelGroupsTable = &schema.Table{
		Name:       "channel_groups",
		Columns:    ChannelGroupsColumns,
		PrimaryKey: []*schema.Column{ChannelGroupsColumns[0], ChannelGroupsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_groups_channel_id",
				Columns:    []*schema.Column{ChannelGroupsColumns[0]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "channel_groups_group_id",
				Columns:    []*schema.Column{ChannelGroupsColumns[1]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserAllowedGroupsColumns holds the columns for the "user_allowed_groups" table.
	UserAllowedGroupsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "group_id", Type: field.TypeInt},
	}
	// UserAllowedGroupsTable holds the schema information for the "user_allowed_groups" table.
	UserAllowedGroupsTable = &schema.Table{
		Name:       "user_allowed_groups",
		Columns:    UserAllowedGroupsColumns,
		PrimaryKey: []*schema.Column{UserAllowedGroupsColumns[0], UserAllowedGroupsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_allowed_groups_user_id",
				Columns:    []*schema.Column{UserAllowedGroupsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_allowed_groups_group_id",
				Columns:    []*schema.Column{UserAllowedGroupsColumns[1]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		AnnouncementsTable,
		AnnouncementReadsTable,
		BalanceLogsTable,
		ChannelsTable,
		GroupsTable,
		ModelPricesTable,
		ModelTagsTable,
		OauthClientsTable,
		PaymentOrdersTable,
		PaymentProviderConfigsTable,
		RedemptionCodesTable,
		SettingsTable,
		UpstreamRequestLogsTable,
		UsageLogsTable,
		UsersTable,
		ChannelGroupsTable,
		UserAllowedGroupsTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = GroupsTable
	APIKeysTable.ForeignKeys[1].RefTable = UsersTable
	BalanceLogsTable.ForeignKeys[0].RefTable = UsersTable
	ModelPricesTable.ForeignKeys[0].RefTable = ModelTagsTable
	UsageLogsTable.ForeignKeys[0].RefTable = APIKeysTable
	UsageLogsTable.ForeignKeys[1].RefTable = ChannelsTable
	UsageLogsTable.ForeignKeys[2].RefTable = GroupsTable
	UsageLogsTable.ForeignKeys[3].RefTable = UsersTable
	ChannelGroupsTable.ForeignKeys[0].RefTable = ChannelsTable
	ChannelGroupsTable.ForeignKeys[1].RefTable = GroupsTable
	UserAllowedGroupsTable.ForeignKeys[0].RefTable = UsersTable
	UserAllowedGroupsTable.ForeignKeys[1].RefTable = GroupsTable
}
