// Code generated by ent, DO NOT EDIT.

package upstreamrequestlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldRequestID, v))
}

// Phase applies equality check predicate on the "phase" field. It's identical to PhaseEQ.
func Phase(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldPhase, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldStatusCode, v))
}

// ErrorType applies equality check predicate on the "error_type" field. It's identical to ErrorTypeEQ.
func ErrorType(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldErrorType, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldErrorCode, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldMessage, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldAttempts, v))
}

// Billed applies equality check predicate on the "billed" field. It's identical to BilledEQ.
func Billed(v bool) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldBilled, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldModel, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldEndpoint, v))
}

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldStream, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldUserID, v))
}

// UserEmailSnapshot applies equality check predicate on the "user_email_snapshot" field. It's identical to UserEmailSnapshotEQ.
func UserEmailSnapshot(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldUserEmailSnapshot, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldGroupID, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldChannelID, v))
}

// ChannelName applies equality check predicate on the "channel_name" field. It's identical to ChannelNameEQ.
func ChannelName(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldChannelName, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldIPAddress, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldUserAgent, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldDurationMs, v))
}

// RepeatCount applies equality check predicate on the "repeat_count" field. It's identical to RepeatCountEQ.
func RepeatCount(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldRepeatCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldCreatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContainsFold(FieldRequestID, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldSource, vs...))
}

// PhaseEQ applies the EQ predicate on the "phase" field.
func PhaseEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldPhase, v))
}

// PhaseNEQ applies the NEQ predicate on the "phase" field.
func PhaseNEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldPhase, v))
}

// PhaseIn applies the In predicate on the "phase" field.
func PhaseIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldPhase, vs...))
}

// PhaseNotIn applies the NotIn predicate on the "phase" field.
func PhaseNotIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldPhase, vs...))
}

// PhaseGT applies the GT predicate on the "phase" field.
func PhaseGT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldPhase, v))
}

// PhaseGTE applies the GTE predicate on the "phase" field.
func PhaseGTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldPhase, v))
}

// PhaseLT applies the LT predicate on the "phase" field.
func PhaseLT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldPhase, v))
}

// PhaseLTE applies the LTE predicate on the "phase" field.
func PhaseLTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldPhase, v))
}

// PhaseContains applies the Contains predicate on the "phase" field.
func PhaseContains(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContains(FieldPhase, v))
}

// PhaseHasPrefix applies the HasPrefix predicate on the "phase" field.
func PhaseHasPrefix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasPrefix(FieldPhase, v))
}

// PhaseHasSuffix applies the HasSuffix predicate on the "phase" field.
func PhaseHasSuffix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasSuffix(FieldPhase, v))
}

// PhaseEqualFold applies the EqualFold predicate on the "phase" field.
func PhaseEqualFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEqualFold(FieldPhase, v))
}

// PhaseContainsFold applies the ContainsFold predicate on the "phase" field.
func PhaseContainsFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContainsFold(FieldPhase, v))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldStatusCode, v))
}

// ErrorTypeEQ applies the EQ predicate on the "error_type" field.
func ErrorTypeEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldErrorType, v))
}

// ErrorTypeNEQ applies the NEQ predicate on the "error_type" field.
func ErrorTypeNEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldErrorType, v))
}

// ErrorTypeIn applies the In predicate on the "error_type" field.
func ErrorTypeIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldErrorType, vs...))
}

// ErrorTypeNotIn applies the NotIn predicate on the "error_type" field.
func ErrorTypeNotIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldErrorType, vs...))
}

// ErrorTypeGT applies the GT predicate on the "error_type" field.
func ErrorTypeGT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldErrorType, v))
}

// ErrorTypeGTE applies the GTE predicate on the "error_type" field.
func ErrorTypeGTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldErrorType, v))
}

// ErrorTypeLT applies the LT predicate on the "error_type" field.
func ErrorTypeLT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldErrorType, v))
}

// ErrorTypeLTE applies the LTE predicate on the "error_type" field.
func ErrorTypeLTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldErrorType, v))
}

// ErrorTypeContains applies the Contains predicate on the "error_type" field.
func ErrorTypeContains(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContains(FieldErrorType, v))
}

// ErrorTypeHasPrefix applies the HasPrefix predicate on the "error_type" field.
func ErrorTypeHasPrefix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasPrefix(FieldErrorType, v))
}

// ErrorTypeHasSuffix applies the HasSuffix predicate on the "error_type" field.
func ErrorTypeHasSuffix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasSuffix(FieldErrorType, v))
}

// ErrorTypeEqualFold applies the EqualFold predicate on the "error_type" field.
func ErrorTypeEqualFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEqualFold(FieldErrorType, v))
}

// ErrorTypeContainsFold applies the ContainsFold predicate on the "error_type" field.
func ErrorTypeContainsFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContainsFold(FieldErrorType, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContainsFold(FieldErrorCode, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContainsFold(FieldMessage, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldAttempts, v))
}

// AttemptChainIsNil applies the IsNil predicate on the "attempt_chain" field.
func AttemptChainIsNil() predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIsNull(FieldAttemptChain))
}

// AttemptChainNotNil applies the NotNil predicate on the "attempt_chain" field.
func AttemptChainNotNil() predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotNull(FieldAttemptChain))
}

// BilledEQ applies the EQ predicate on the "billed" field.
func BilledEQ(v bool) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldBilled, v))
}

// BilledNEQ applies the NEQ predicate on the "billed" field.
func BilledNEQ(v bool) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldBilled, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContainsFold(FieldModel, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContainsFold(FieldEndpoint, v))
}

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldStream, v))
}

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldStream, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldUserID, v))
}

// UserEmailSnapshotEQ applies the EQ predicate on the "user_email_snapshot" field.
func UserEmailSnapshotEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotNEQ applies the NEQ predicate on the "user_email_snapshot" field.
func UserEmailSnapshotNEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotIn applies the In predicate on the "user_email_snapshot" field.
func UserEmailSnapshotIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldUserEmailSnapshot, vs...))
}

// UserEmailSnapshotNotIn applies the NotIn predicate on the "user_email_snapshot" field.
func UserEmailSnapshotNotIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldUserEmailSnapshot, vs...))
}

// UserEmailSnapshotGT applies the GT predicate on the "user_email_snapshot" field.
func UserEmailSnapshotGT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotGTE applies the GTE predicate on the "user_email_snapshot" field.
func UserEmailSnapshotGTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotLT applies the LT predicate on the "user_email_snapshot" field.
func UserEmailSnapshotLT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotLTE applies the LTE predicate on the "user_email_snapshot" field.
func UserEmailSnapshotLTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotContains applies the Contains predicate on the "user_email_snapshot" field.
func UserEmailSnapshotContains(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContains(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotHasPrefix applies the HasPrefix predicate on the "user_email_snapshot" field.
func UserEmailSnapshotHasPrefix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasPrefix(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotHasSuffix applies the HasSuffix predicate on the "user_email_snapshot" field.
func UserEmailSnapshotHasSuffix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasSuffix(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotEqualFold applies the EqualFold predicate on the "user_email_snapshot" field.
func UserEmailSnapshotEqualFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEqualFold(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotContainsFold applies the ContainsFold predicate on the "user_email_snapshot" field.
func UserEmailSnapshotContainsFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContainsFold(FieldUserEmailSnapshot, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldAPIKeyID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldGroupID, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldChannelID, v))
}

// ChannelNameEQ applies the EQ predicate on the "channel_name" field.
func ChannelNameEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldChannelName, v))
}

// ChannelNameNEQ applies the NEQ predicate on the "channel_name" field.
func ChannelNameNEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldChannelName, v))
}

// ChannelNameIn applies the In predicate on the "channel_name" field.
func ChannelNameIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldChannelName, vs...))
}

// ChannelNameNotIn applies the NotIn predicate on the "channel_name" field.
func ChannelNameNotIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldChannelName, vs...))
}

// ChannelNameGT applies the GT predicate on the "channel_name" field.
func ChannelNameGT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldChannelName, v))
}

// ChannelNameGTE applies the GTE predicate on the "channel_name" field.
func ChannelNameGTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldChannelName, v))
}

// ChannelNameLT applies the LT predicate on the "channel_name" field.
func ChannelNameLT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldChannelName, v))
}

// ChannelNameLTE applies the LTE predicate on the "channel_name" field.
func ChannelNameLTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldChannelName, v))
}

// ChannelNameContains applies the Contains predicate on the "channel_name" field.
func ChannelNameContains(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContains(FieldChannelName, v))
}

// ChannelNameHasPrefix applies the HasPrefix predicate on the "channel_name" field.
func ChannelNameHasPrefix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasPrefix(FieldChannelName, v))
}

// ChannelNameHasSuffix applies the HasSuffix predicate on the "channel_name" field.
func ChannelNameHasSuffix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasSuffix(FieldChannelName, v))
}

// ChannelNameEqualFold applies the EqualFold predicate on the "channel_name" field.
func ChannelNameEqualFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEqualFold(FieldChannelName, v))
}

// ChannelNameContainsFold applies the ContainsFold predicate on the "channel_name" field.
func ChannelNameContainsFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContainsFold(FieldChannelName, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContainsFold(FieldIPAddress, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldContainsFold(FieldUserAgent, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldDurationMs, v))
}

// RepeatCountEQ applies the EQ predicate on the "repeat_count" field.
func RepeatCountEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldRepeatCount, v))
}

// RepeatCountNEQ applies the NEQ predicate on the "repeat_count" field.
func RepeatCountNEQ(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldRepeatCount, v))
}

// RepeatCountIn applies the In predicate on the "repeat_count" field.
func RepeatCountIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldRepeatCount, vs...))
}

// RepeatCountNotIn applies the NotIn predicate on the "repeat_count" field.
func RepeatCountNotIn(vs ...int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldRepeatCount, vs...))
}

// RepeatCountGT applies the GT predicate on the "repeat_count" field.
func RepeatCountGT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldRepeatCount, v))
}

// RepeatCountGTE applies the GTE predicate on the "repeat_count" field.
func RepeatCountGTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldRepeatCount, v))
}

// RepeatCountLT applies the LT predicate on the "repeat_count" field.
func RepeatCountLT(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldRepeatCount, v))
}

// RepeatCountLTE applies the LTE predicate on the "repeat_count" field.
func RepeatCountLTE(v int) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldRepeatCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamRequestLog) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamRequestLog) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamRequestLog) predicate.UpstreamRequestLog {
	return predicate.UpstreamRequestLog(sql.NotPredicates(p))
}
